package legionnaire_os;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class About_Us extends javax.swing.JFrame {

    /**
     * Creates new form About_Us
     */
    public About_Us() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AboutUs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AboutContent = new javax.swing.JTextArea();
        Createdbylabel = new javax.swing.JLabel();
        Closebutton = new javax.swing.JButton();
        AboutUslabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutUs.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        AboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutUs.setText("About Us");
        getContentPane().add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 250, 40));

        AboutContent.setEditable(false);
        AboutContent.setColumns(20);
        AboutContent.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        AboutContent.setLineWrap(true);
        AboutContent.setRows(5);
        AboutContent.setText("Hey there!!\nWe are students of class XII currently persueing IP as an optional subject. As our annual project we made Legionnaire OS Simulator which would function similar to an Android interface.\n\nIt's a user friendly interface which can be operated by authorised user.\n\nAs an enthusiast, we introduced some extra features in our project which help us learn more.");
        AboutContent.setWrapStyleWord(true);
        AboutContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AboutContent.setOpaque(false);
        jScrollPane1.setViewportView(AboutContent);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, 430));

        Createdbylabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Createdbylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Createdbylabel.setText("Created by: Mandeep Dalavi and Ajay Babu");
        getContentPane().add(Createdbylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 540, 50));

        Closebutton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Closebutton.setText("Close");
        Closebutton.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red, 2));
        Closebutton.setContentAreaFilled(false);
        Closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 110, -1));

        AboutUslabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/contact back4.jpg"))); // NOI18N
        getContentPane().add(AboutUslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.setOpaque(true);
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(636, 740);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void ClosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebuttonActionPerformed
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ClosebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About_Us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About_Us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About_Us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About_Us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About_Us().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AboutContent;
    private javax.swing.JLabel AboutUs;
    private javax.swing.JLabel AboutUslabel;
    private javax.swing.JButton Closebutton;
    private javax.swing.JLabel Createdbylabel;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
