package legionnaire_os;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Apps extends javax.swing.JFrame {

    /**
     * Creates new form Apps
     */
    public Apps() {
        initComponents();
        
//---------------------JDBC part getting background--------------------------------//
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "SELECT * from Backgrounds";
        ResultSet rs = stmt.executeQuery(query);
        if (rs.first()) 
        {
            String homebackg = rs.getString(1);
            Appslabel.setIcon(new ImageIcon(getClass().getResource(homebackg)));
        }
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(null, "Error in Connectivity!");
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculatorapp = new javax.swing.JButton();
        Contactsapp = new javax.swing.JButton();
        BullandCowsapp = new javax.swing.JButton();
        GrizzyBearapp = new javax.swing.JButton();
        NextPrimeNoapp = new javax.swing.JButton();
        AboutUsapp = new javax.swing.JButton();
        Settingapp = new javax.swing.JButton();
        BullsandCowslabel = new javax.swing.JLabel();
        Contactslabel = new javax.swing.JLabel();
        GrizzyBearlabel = new javax.swing.JLabel();
        Calculatorlabel = new javax.swing.JLabel();
        NextPrimeNolabel = new javax.swing.JLabel();
        AboutUslabel = new javax.swing.JLabel();
        Settinglabel = new javax.swing.JLabel();
        MoreAppslabel = new javax.swing.JLabel();
        Appslabel = new javax.swing.JLabel();
        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Calculatorapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/calculator-icon--2-.png"))); // NOI18N
        Calculatorapp.setContentAreaFilled(false);
        Calculatorapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorappActionPerformed(evt);
            }
        });
        getContentPane().add(Calculatorapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 110));

        Contactsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/contacts icon.png"))); // NOI18N
        Contactsapp.setContentAreaFilled(false);
        Contactsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsappActionPerformed(evt);
            }
        });
        getContentPane().add(Contactsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, -1));

        BullandCowsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/game icon.png"))); // NOI18N
        BullandCowsapp.setContentAreaFilled(false);
        BullandCowsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BullandCowsappActionPerformed(evt);
            }
        });
        getContentPane().add(BullandCowsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 120, -1));

        GrizzyBearapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/icon_billing--1-.png"))); // NOI18N
        GrizzyBearapp.setContentAreaFilled(false);
        GrizzyBearapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrizzyBearappActionPerformed(evt);
            }
        });
        getContentPane().add(GrizzyBearapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 120, -1));

        NextPrimeNoapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/nextprime.png"))); // NOI18N
        NextPrimeNoapp.setContentAreaFilled(false);
        NextPrimeNoapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextPrimeNoappActionPerformed(evt);
            }
        });
        getContentPane().add(NextPrimeNoapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 100, 100));

        AboutUsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/about-us-icon-15 (1).png"))); // NOI18N
        AboutUsapp.setContentAreaFilled(false);
        AboutUsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsappActionPerformed(evt);
            }
        });
        getContentPane().add(AboutUsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));

        Settingapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/settings-l-icon--1-.png"))); // NOI18N
        Settingapp.setContentAreaFilled(false);
        Settingapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingappActionPerformed(evt);
            }
        });
        getContentPane().add(Settingapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 120, -1));

        BullsandCowslabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        BullsandCowslabel.setForeground(new java.awt.Color(255, 255, 255));
        BullsandCowslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BullsandCowslabel.setText("Bulls and Cows");
        getContentPane().add(BullsandCowslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 170, 30));

        Contactslabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Contactslabel.setForeground(new java.awt.Color(255, 255, 255));
        Contactslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contactslabel.setText("Contacts");
        getContentPane().add(Contactslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 100, 30));

        GrizzyBearlabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        GrizzyBearlabel.setForeground(new java.awt.Color(255, 255, 255));
        GrizzyBearlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GrizzyBearlabel.setText("Grizzy Bear");
        getContentPane().add(GrizzyBearlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 130, 30));

        Calculatorlabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Calculatorlabel.setForeground(new java.awt.Color(255, 255, 255));
        Calculatorlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calculatorlabel.setText("Calculator+");
        getContentPane().add(Calculatorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 30));

        NextPrimeNolabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        NextPrimeNolabel.setForeground(new java.awt.Color(255, 255, 255));
        NextPrimeNolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextPrimeNolabel.setText("Next Prime No.");
        getContentPane().add(NextPrimeNolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 180, 30));

        AboutUslabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        AboutUslabel.setForeground(new java.awt.Color(255, 255, 255));
        AboutUslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutUslabel.setText("About Us");
        getContentPane().add(AboutUslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        Settinglabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Settinglabel.setForeground(new java.awt.Color(255, 255, 255));
        Settinglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settinglabel.setText("Setting");
        getContentPane().add(Settinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        MoreAppslabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        MoreAppslabel.setForeground(new java.awt.Color(255, 255, 255));
        MoreAppslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MoreAppslabel.setText("More Apps coming soon...");
        getContentPane().add(MoreAppslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 290, -1));

        Appslabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Appslabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back3.jpg"))); // NOI18N
        Appslabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Appslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 60));

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.setOpaque(true);
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingappActionPerformed
new Setting_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingappActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void CalculatorappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorappActionPerformed
new Calculator_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculatorappActionPerformed

    private void ContactsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsappActionPerformed
new Contacts_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactsappActionPerformed

    private void AboutUsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsappActionPerformed
new About_Us().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsappActionPerformed

    private void GrizzyBearappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrizzyBearappActionPerformed
new GrizzlyBear_Login().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_GrizzyBearappActionPerformed

    private void NextPrimeNoappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextPrimeNoappActionPerformed
new Next_Prime_No_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_NextPrimeNoappActionPerformed

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1025, 707);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void BullandCowsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BullandCowsappActionPerformed
new Bulls_and_Cows().setVisible(true);
new Enter_no().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BullandCowsappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsapp;
    private javax.swing.JLabel AboutUslabel;
    private javax.swing.JMenuItem AboutUsmenu;
    public javax.swing.JLabel Appslabel;
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton BullandCowsapp;
    private javax.swing.JLabel BullsandCowslabel;
    private javax.swing.JButton Calculatorapp;
    private javax.swing.JLabel Calculatorlabel;
    private javax.swing.JButton Contactsapp;
    private javax.swing.JLabel Contactslabel;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JButton GrizzyBearapp;
    private javax.swing.JLabel GrizzyBearlabel;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel MoreAppslabel;
    private javax.swing.JButton NextPrimeNoapp;
    private javax.swing.JLabel NextPrimeNolabel;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JButton Settingapp;
    private javax.swing.JLabel Settinglabel;
    // End of variables declaration//GEN-END:variables
}
