/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legionnaire_os;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Bulls_and_Cows extends javax.swing.JFrame {
    Enter_no enter = new Enter_no();
    int wordcount = 1;
    int trycount = 1;

    /**
     * Creates new form Bulls_and_Cows
     */
    public Bulls_and_Cows() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        inputlabel1 = new javax.swing.JLabel();
        inputlabel2 = new javax.swing.JLabel();
        inputlabel3 = new javax.swing.JLabel();
        inputlabel4 = new javax.swing.JLabel();
        inputlabel5 = new javax.swing.JLabel();
        inputlabel6 = new javax.swing.JLabel();
        inputlabel7 = new javax.swing.JLabel();
        inputlabel8 = new javax.swing.JLabel();
        inputlabel9 = new javax.swing.JLabel();
        inputlabel10 = new javax.swing.JLabel();
        bullslabel1 = new javax.swing.JLabel();
        bullslabel2 = new javax.swing.JLabel();
        bullslabel3 = new javax.swing.JLabel();
        bullslabel4 = new javax.swing.JLabel();
        bullslabel5 = new javax.swing.JLabel();
        bullslabel6 = new javax.swing.JLabel();
        bullslabel7 = new javax.swing.JLabel();
        bullslabel8 = new javax.swing.JLabel();
        bullslabel9 = new javax.swing.JLabel();
        bullslabel10 = new javax.swing.JLabel();
        cowslabel5 = new javax.swing.JLabel();
        cowslabel4 = new javax.swing.JLabel();
        cowslabel10 = new javax.swing.JLabel();
        cowslabel1 = new javax.swing.JLabel();
        cowslabel6 = new javax.swing.JLabel();
        cowslabel3 = new javax.swing.JLabel();
        cowslabel7 = new javax.swing.JLabel();
        cowslabel9 = new javax.swing.JLabel();
        cowslabel2 = new javax.swing.JLabel();
        cowslabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Bullslabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel);
        Powerpanel.setBounds(0, 580, 1030, 71);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bulls and Cows");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 280, 40);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Guess");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 90, 110, 30);

        inputTF.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        getContentPane().add(inputTF);
        inputTF.setBounds(730, 90, 190, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(930, 90, 73, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 180, 50, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bulls");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 140, 37, 23);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cows");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(700, 140, 48, 23);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sr.No.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 140, 50, 23);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 220, 50, 23);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("3.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 260, 50, 23);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("4.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 300, 50, 23);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("5.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 340, 50, 23);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("6.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 380, 50, 23);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("7.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 420, 50, 23);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("8.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 460, 50, 23);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("9.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 500, 50, 23);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("10.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 540, 50, 23);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Your Input");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 140, 120, 23);

        inputlabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel1.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel1.setToolTipText("");
        getContentPane().add(inputlabel1);
        inputlabel1.setBounds(200, 180, 120, 20);

        inputlabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel2.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel2.setToolTipText("");
        getContentPane().add(inputlabel2);
        inputlabel2.setBounds(200, 220, 120, 20);

        inputlabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel3.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel3.setToolTipText("");
        getContentPane().add(inputlabel3);
        inputlabel3.setBounds(200, 260, 120, 20);

        inputlabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel4.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel4.setToolTipText("");
        getContentPane().add(inputlabel4);
        inputlabel4.setBounds(200, 300, 120, 20);

        inputlabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel5.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel5.setToolTipText("");
        getContentPane().add(inputlabel5);
        inputlabel5.setBounds(200, 340, 120, 20);

        inputlabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel6.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel6.setToolTipText("");
        getContentPane().add(inputlabel6);
        inputlabel6.setBounds(200, 380, 120, 20);

        inputlabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel7.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel7.setToolTipText("");
        getContentPane().add(inputlabel7);
        inputlabel7.setBounds(200, 420, 120, 20);

        inputlabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel8.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel8.setToolTipText("");
        getContentPane().add(inputlabel8);
        inputlabel8.setBounds(200, 460, 120, 20);

        inputlabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel9.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel9.setToolTipText("");
        getContentPane().add(inputlabel9);
        inputlabel9.setBounds(200, 500, 120, 20);

        inputlabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputlabel10.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputlabel10.setToolTipText("");
        getContentPane().add(inputlabel10);
        inputlabel10.setBounds(200, 540, 120, 20);

        bullslabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel1.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel1.setToolTipText("");
        getContentPane().add(bullslabel1);
        bullslabel1.setBounds(440, 180, 120, 20);

        bullslabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel2.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel2.setToolTipText("");
        getContentPane().add(bullslabel2);
        bullslabel2.setBounds(440, 220, 120, 20);

        bullslabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel3.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel3.setToolTipText("");
        getContentPane().add(bullslabel3);
        bullslabel3.setBounds(440, 260, 120, 20);

        bullslabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel4.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel4.setToolTipText("");
        getContentPane().add(bullslabel4);
        bullslabel4.setBounds(440, 300, 120, 20);

        bullslabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel5.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel5.setToolTipText("");
        getContentPane().add(bullslabel5);
        bullslabel5.setBounds(440, 340, 120, 20);

        bullslabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel6.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel6.setToolTipText("");
        getContentPane().add(bullslabel6);
        bullslabel6.setBounds(440, 380, 120, 20);

        bullslabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel7.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel7.setToolTipText("");
        getContentPane().add(bullslabel7);
        bullslabel7.setBounds(440, 420, 120, 20);

        bullslabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel8.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel8.setToolTipText("");
        getContentPane().add(bullslabel8);
        bullslabel8.setBounds(440, 460, 120, 20);

        bullslabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel9.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel9.setToolTipText("");
        getContentPane().add(bullslabel9);
        bullslabel9.setBounds(440, 500, 120, 20);

        bullslabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bullslabel10.setForeground(new java.awt.Color(255, 255, 255));
        bullslabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullslabel10.setToolTipText("");
        getContentPane().add(bullslabel10);
        bullslabel10.setBounds(440, 540, 120, 20);

        cowslabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel5.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel5.setToolTipText("");
        getContentPane().add(cowslabel5);
        cowslabel5.setBounds(670, 340, 120, 20);

        cowslabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel4.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel4.setToolTipText("");
        getContentPane().add(cowslabel4);
        cowslabel4.setBounds(670, 300, 120, 20);

        cowslabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel10.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel10.setToolTipText("");
        getContentPane().add(cowslabel10);
        cowslabel10.setBounds(670, 540, 120, 20);

        cowslabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel1.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel1.setToolTipText("");
        getContentPane().add(cowslabel1);
        cowslabel1.setBounds(670, 180, 120, 20);

        cowslabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel6.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel6.setToolTipText("");
        getContentPane().add(cowslabel6);
        cowslabel6.setBounds(670, 380, 120, 20);

        cowslabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel3.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel3.setToolTipText("");
        getContentPane().add(cowslabel3);
        cowslabel3.setBounds(670, 260, 120, 20);

        cowslabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel7.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel7.setToolTipText("");
        getContentPane().add(cowslabel7);
        cowslabel7.setBounds(670, 420, 120, 20);

        cowslabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel9.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel9.setToolTipText("");
        getContentPane().add(cowslabel9);
        cowslabel9.setBounds(670, 500, 120, 20);

        cowslabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel2.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel2.setToolTipText("");
        getContentPane().add(cowslabel2);
        cowslabel2.setBounds(670, 220, 120, 20);

        cowslabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cowslabel8.setForeground(new java.awt.Color(255, 255, 255));
        cowslabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowslabel8.setToolTipText("");
        getContentPane().add(cowslabel8);
        cowslabel8.setBounds(670, 460, 120, 20);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setText("Restart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(820, 300, 170, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.red);
        jLabel17.setText("Go to Help to see Instructions");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 10, 240, 30);

        Bullslabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/game back2.jpg"))); // NOI18N
        getContentPane().add(Bullslabel);
        Bullslabel.setBounds(0, 0, 1024, 577);

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.setOpaque(true);
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("How to play");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Helpmenu.add(jMenuItem1);

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
        new Apps().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
        new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1025, 707);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = inputTF.getText();
        if (input.length() != 4) 
        {
            JOptionPane.showMessageDialog(this, "Please enter a 4 digit word");
            inputTF.setText("");
        }
        else 
        {
            if (trycount <= 10) 
            {
                int bulls = 0;
                int cows = 0;
                String word = new String();
                char inputch;
                char wordch;
                try 
                {
                    Class.forName("java.sql.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Mandroid", "root", "mandy15012001");
                    Statement stmt = con.createStatement();
                    String query = "Select word from words where srno=" + wordcount;
                    ResultSet rs = stmt.executeQuery(query);
                    if (rs.first()) 
                    {
                        word = rs.getString(1);
                    }
                } 
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(this, "Error in Connectivity!");
                }
                for (int i = 0; i < word.length(); i++) 
                {
                    for (int j = 0; j < input.length();) 
                    {
                        wordch = word.charAt(i);
                        if (i == j) 
                        {
                            j++;
                        }
                        else 
                        {
                            inputch = input.charAt(j);
                            if (inputch == wordch) 
                            {
                                cows++;
                            }
                            j++;
                        }
                    }
                }
                for (int i = 0; i < word.length(); i++) 
                {
                    wordch = word.charAt(i);
                    inputch = input.charAt(i);
                    if (inputch == wordch) 
                    {
                        bulls++;
                    }
                }
                switch (trycount) {
                    case 1:
                        inputlabel1.setText(input);
                        bullslabel1.setText(bulls + "");
                        cowslabel1.setText(cows + "");
                        break;
                    case 2:
                        inputlabel2.setText(input);
                        bullslabel2.setText(bulls + "");
                        cowslabel2.setText(cows + "");
                        break;
                    case 3:
                        inputlabel3.setText(input);
                        bullslabel3.setText(bulls + "");
                        cowslabel3.setText(cows + "");
                        break;
                    case 4:
                        inputlabel4.setText(input);
                        bullslabel4.setText(bulls + "");
                        cowslabel4.setText(cows + "");
                        break;
                    case 5:
                        inputlabel5.setText(input);
                        bullslabel5.setText(bulls + "");
                        cowslabel5.setText(cows + "");
                        break;
                    case 6:
                        inputlabel6.setText(input);
                        bullslabel6.setText(bulls + "");
                        cowslabel6.setText(cows + "");
                        break;
                    case 7:
                        inputlabel7.setText(input);
                        bullslabel7.setText(bulls + "");
                        cowslabel7.setText(cows + "");
                        break;
                    case 8:
                        inputlabel8.setText(input);
                        bullslabel8.setText(bulls + "");
                        cowslabel8.setText(cows + "");
                        break;
                    case 9:
                        inputlabel9.setText(input);
                        bullslabel9.setText(bulls + "");
                        cowslabel9.setText(cows + "");
                        break;
                    case 10:
                        inputlabel10.setText(input);
                        bullslabel10.setText(bulls + "");
                        cowslabel10.setText(cows + "");
                        break;
                    default:
                        break;
                }
                if (trycount == 10 && bulls != 4) 
                {
                    JOptionPane.showMessageDialog(this, "Sorry! You lost. The word is- " + word + ".", "You Lost", JOptionPane.PLAIN_MESSAGE);
                    inputTF.setText("");
                    inputlabel1.setText("");
                    bullslabel1.setText("");
                    cowslabel1.setText("");
                    inputlabel2.setText("");
                    bullslabel2.setText("");
                    cowslabel2.setText("");
                    inputlabel3.setText("");
                    bullslabel3.setText("");
                    cowslabel3.setText("");
                    inputlabel4.setText("");
                    bullslabel4.setText("");
                    cowslabel4.setText("");
                    inputlabel5.setText("");
                    bullslabel5.setText("");
                    cowslabel5.setText("");
                    inputlabel6.setText("");
                    bullslabel6.setText("");
                    cowslabel6.setText("");
                    inputlabel7.setText("");
                    bullslabel7.setText("");
                    cowslabel7.setText("");
                    inputlabel8.setText("");
                    bullslabel8.setText("");
                    cowslabel8.setText("");
                    inputlabel9.setText("");
                    bullslabel9.setText("");
                    cowslabel9.setText("");
                    inputlabel10.setText("");
                    bullslabel10.setText("");
                    cowslabel10.setText("");
                    trycount = 0;
                    if (wordcount <= 40) 
                    {
                        wordcount++;
                    }
                    else 
                    {
                        wordcount = 1;
                    }
                }
                trycount++;
                if (bulls == 4) 
                {
                    JOptionPane.showMessageDialog(this, "You got that!", "You won", JOptionPane.PLAIN_MESSAGE);
                    inputTF.setText("");
                    inputlabel1.setText("");
                    bullslabel1.setText("");
                    cowslabel1.setText("");
                    inputlabel2.setText("");
                    bullslabel2.setText("");
                    cowslabel2.setText("");
                    inputlabel3.setText("");
                    bullslabel3.setText("");
                    cowslabel3.setText("");
                    inputlabel4.setText("");
                    bullslabel4.setText("");
                    cowslabel4.setText("");
                    inputlabel5.setText("");
                    bullslabel5.setText("");
                    cowslabel5.setText("");
                    inputlabel6.setText("");
                    bullslabel6.setText("");
                    cowslabel6.setText("");
                    inputlabel7.setText("");
                    bullslabel7.setText("");
                    cowslabel7.setText("");
                    inputlabel8.setText("");
                    bullslabel8.setText("");
                    cowslabel8.setText("");
                    inputlabel9.setText("");
                    bullslabel9.setText("");
                    cowslabel9.setText("");
                    inputlabel10.setText("");
                    bullslabel10.setText("");
                    cowslabel10.setText("");
                    trycount = 1;
                    if (wordcount <= 40) 
                    {
                        wordcount++;
                    } 
                    else 
                    {
                        wordcount = 1;
                    }
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "Sorry! You have no more tries left..", "No tries left", JOptionPane.WARNING_MESSAGE);
            }
        }
        inputTF.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        inputTF.setText("");
        inputlabel1.setText("");
        bullslabel1.setText("");
        cowslabel1.setText("");
        inputlabel2.setText("");
        bullslabel2.setText("");
        cowslabel2.setText("");
        inputlabel3.setText("");
        bullslabel3.setText("");
        cowslabel3.setText("");
        inputlabel4.setText("");
        bullslabel4.setText("");
        cowslabel4.setText("");
        inputlabel5.setText("");
        bullslabel5.setText("");
        cowslabel5.setText("");
        inputlabel6.setText("");
        bullslabel6.setText("");
        cowslabel6.setText("");
        inputlabel7.setText("");
        bullslabel7.setText("");
        cowslabel7.setText("");
        inputlabel8.setText("");
        bullslabel8.setText("");
        cowslabel8.setText("");
        inputlabel9.setText("");
        bullslabel9.setText("");
        cowslabel9.setText("");
        inputlabel10.setText("");
        bullslabel10.setText("");
        cowslabel10.setText("");
        trycount = 1;
        if (wordcount <= 40) 
        {
            wordcount++;
        }
        else 
        {
            wordcount = 1;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new How_to_Play().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bulls_and_Cows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bulls_and_Cows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bulls_and_Cows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bulls_and_Cows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bulls_and_Cows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel Bullslabel;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JLabel bullslabel1;
    private javax.swing.JLabel bullslabel10;
    private javax.swing.JLabel bullslabel2;
    private javax.swing.JLabel bullslabel3;
    private javax.swing.JLabel bullslabel4;
    private javax.swing.JLabel bullslabel5;
    private javax.swing.JLabel bullslabel6;
    private javax.swing.JLabel bullslabel7;
    private javax.swing.JLabel bullslabel8;
    private javax.swing.JLabel bullslabel9;
    private javax.swing.JLabel cowslabel1;
    private javax.swing.JLabel cowslabel10;
    private javax.swing.JLabel cowslabel2;
    private javax.swing.JLabel cowslabel3;
    private javax.swing.JLabel cowslabel4;
    private javax.swing.JLabel cowslabel5;
    private javax.swing.JLabel cowslabel6;
    private javax.swing.JLabel cowslabel7;
    private javax.swing.JLabel cowslabel8;
    private javax.swing.JLabel cowslabel9;
    private javax.swing.JTextField inputTF;
    private javax.swing.JLabel inputlabel1;
    private javax.swing.JLabel inputlabel10;
    private javax.swing.JLabel inputlabel2;
    private javax.swing.JLabel inputlabel3;
    private javax.swing.JLabel inputlabel4;
    private javax.swing.JLabel inputlabel5;
    private javax.swing.JLabel inputlabel6;
    private javax.swing.JLabel inputlabel7;
    private javax.swing.JLabel inputlabel8;
    private javax.swing.JLabel inputlabel9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
