package legionnaire_os;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Calculator_App extends javax.swing.JFrame {
    double firstnum, secondnum, result;
    String operations;
    private Object math;
    
    /**
     * Creates new form Calculator_App
     */
    public Calculator_App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Separator = new javax.swing.JSeparator();
        Onebutton = new javax.swing.JButton();
        Twobutton = new javax.swing.JButton();
        Threebutton = new javax.swing.JButton();
        Fourbutton = new javax.swing.JButton();
        Fivebutton = new javax.swing.JButton();
        Sixbutton = new javax.swing.JButton();
        Sevenbutton = new javax.swing.JButton();
        Eightbutton = new javax.swing.JButton();
        Ninebutton = new javax.swing.JButton();
        Zerobutton = new javax.swing.JButton();
        x2button = new javax.swing.JButton();
        Dividebutton = new javax.swing.JButton();
        Multiplybutton = new javax.swing.JButton();
        DotButton = new javax.swing.JButton();
        ACbutton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        Subtractbutton = new javax.swing.JButton();
        Addbutton = new javax.swing.JButton();
        Equalbutton = new javax.swing.JButton();
        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        Logbutton1 = new javax.swing.JButton();
        Cosbutton = new javax.swing.JButton();
        Sinhbutton = new javax.swing.JButton();
        Coshbutton = new javax.swing.JButton();
        Tanbutton = new javax.swing.JButton();
        xybutton = new javax.swing.JButton();
        Sinbutton = new javax.swing.JButton();
        Sqrtbutton = new javax.swing.JButton();
        Tanhbutton = new javax.swing.JButton();
        x3button = new javax.swing.JButton();
        piebutton = new javax.swing.JButton();
        Plusminusbutton = new javax.swing.JButton();
        Cbrbutton = new javax.swing.JButton();
        Roundbutton = new javax.swing.JButton();
        Hexbutton = new javax.swing.JButton();
        Binbutton = new javax.swing.JButton();
        Modbutton = new javax.swing.JButton();
        lnxbutton = new javax.swing.JButton();
        Degbutton = new javax.swing.JButton();
        Radbutton = new javax.swing.JButton();
        Octalbutton = new javax.swing.JButton();
        Calculatorlabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Standard = new javax.swing.JMenuItem();
        Scientific = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Separator.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 10));

        Onebutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Onebutton.setText("1");
        Onebutton.setContentAreaFilled(false);
        Onebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Onebutton.setOpaque(true);
        Onebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Onebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 50, 50));

        Twobutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Twobutton.setText("2");
        Twobutton.setContentAreaFilled(false);
        Twobutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Twobutton.setOpaque(true);
        Twobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwobuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Twobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 50, 50));

        Threebutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Threebutton.setText("3");
        Threebutton.setContentAreaFilled(false);
        Threebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Threebutton.setOpaque(true);
        Threebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Threebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 50, 50));

        Fourbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Fourbutton.setText("4");
        Fourbutton.setContentAreaFilled(false);
        Fourbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fourbutton.setOpaque(true);
        Fourbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Fourbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 50));

        Fivebutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Fivebutton.setText("5");
        Fivebutton.setContentAreaFilled(false);
        Fivebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fivebutton.setOpaque(true);
        Fivebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FivebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Fivebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, 50));

        Sixbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Sixbutton.setText("6");
        Sixbutton.setContentAreaFilled(false);
        Sixbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sixbutton.setOpaque(true);
        Sixbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Sixbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 50, 50));

        Sevenbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Sevenbutton.setText("7");
        Sevenbutton.setContentAreaFilled(false);
        Sevenbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sevenbutton.setOpaque(true);
        Sevenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Sevenbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 50));

        Eightbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Eightbutton.setText("8");
        Eightbutton.setContentAreaFilled(false);
        Eightbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eightbutton.setOpaque(true);
        Eightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Eightbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, 50));

        Ninebutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Ninebutton.setText("9");
        Ninebutton.setContentAreaFilled(false);
        Ninebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ninebutton.setOpaque(true);
        Ninebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NinebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Ninebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 50, 50));

        Zerobutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Zerobutton.setText("0");
        Zerobutton.setContentAreaFilled(false);
        Zerobutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Zerobutton.setOpaque(true);
        Zerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZerobuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Zerobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 50, 50));

        x2button.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        x2button.setText("x^2");
        x2button.setContentAreaFilled(false);
        x2button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        x2button.setOpaque(true);
        x2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2buttonActionPerformed(evt);
            }
        });
        getContentPane().add(x2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 80, 50));

        Dividebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Dividebutton.setText("/");
        Dividebutton.setContentAreaFilled(false);
        Dividebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dividebutton.setOpaque(true);
        Dividebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DividebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Dividebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 50));

        Multiplybutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Multiplybutton.setText("x");
        Multiplybutton.setContentAreaFilled(false);
        Multiplybutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Multiplybutton.setOpaque(true);
        Multiplybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Multiplybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, 50));

        DotButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DotButton.setText(".");
        DotButton.setContentAreaFilled(false);
        DotButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DotButton.setOpaque(true);
        DotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 50, 50));

        ACbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ACbutton.setText("AC");
        ACbutton.setContentAreaFilled(false);
        ACbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ACbutton.setOpaque(true);
        ACbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(ACbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 50));

        Deletebutton.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        Deletebutton.setText("←");
        Deletebutton.setContentAreaFilled(false);
        Deletebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Deletebutton.setOpaque(true);
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, 50));

        Subtractbutton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Subtractbutton.setText("-");
        Subtractbutton.setContentAreaFilled(false);
        Subtractbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Subtractbutton.setOpaque(true);
        Subtractbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Subtractbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 90, 50));

        Addbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Addbutton.setText("+");
        Addbutton.setContentAreaFilled(false);
        Addbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Addbutton.setOpaque(true);
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 50));

        Equalbutton.setBackground(new java.awt.Color(204, 204, 255));
        Equalbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Equalbutton.setText("=");
        Equalbutton.setContentAreaFilled(false);
        Equalbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Equalbutton.setOpaque(true);
        Equalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Equalbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 90, 50));

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));
        Powerpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(Backbutton))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 60));

        input.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        input.setToolTipText("");
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));

        Logbutton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Logbutton1.setText("log");
        Logbutton1.setContentAreaFilled(false);
        Logbutton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logbutton1.setOpaque(true);
        Logbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Logbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 80, 50));

        Cosbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Cosbutton.setText("cos");
        Cosbutton.setContentAreaFilled(false);
        Cosbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cosbutton.setOpaque(true);
        Cosbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Cosbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 70, 50));

        Sinhbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Sinhbutton.setText("sinh");
        Sinhbutton.setContentAreaFilled(false);
        Sinhbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sinhbutton.setOpaque(true);
        Sinhbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinhbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Sinhbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 100, 50));

        Coshbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Coshbutton.setText("cosh");
        Coshbutton.setContentAreaFilled(false);
        Coshbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Coshbutton.setOpaque(true);
        Coshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoshbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Coshbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 100, 50));

        Tanbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Tanbutton.setText("tan");
        Tanbutton.setContentAreaFilled(false);
        Tanbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tanbutton.setOpaque(true);
        Tanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Tanbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, 50));

        xybutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        xybutton.setText("x^y");
        xybutton.setContentAreaFilled(false);
        xybutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xybutton.setOpaque(true);
        xybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(xybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, 50));

        Sinbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Sinbutton.setText("sin");
        Sinbutton.setContentAreaFilled(false);
        Sinbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sinbutton.setOpaque(true);
        Sinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Sinbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 70, 50));

        Sqrtbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Sqrtbutton.setText("√");
        Sqrtbutton.setContentAreaFilled(false);
        Sqrtbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sqrtbutton.setOpaque(true);
        Sqrtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Sqrtbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, 50));

        Tanhbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Tanhbutton.setText("tanh");
        Tanhbutton.setContentAreaFilled(false);
        Tanhbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tanhbutton.setOpaque(true);
        Tanhbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanhbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Tanhbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 100, 50));

        x3button.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        x3button.setText("x^3");
        x3button.setContentAreaFilled(false);
        x3button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        x3button.setOpaque(true);
        x3button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3buttonActionPerformed(evt);
            }
        });
        getContentPane().add(x3button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, 50));

        piebutton.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        piebutton.setText("∏");
        piebutton.setContentAreaFilled(false);
        piebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        piebutton.setOpaque(true);
        piebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(piebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 80, 50));

        Plusminusbutton.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        Plusminusbutton.setText("±");
        Plusminusbutton.setContentAreaFilled(false);
        Plusminusbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Plusminusbutton.setOpaque(true);
        Plusminusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusminusbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Plusminusbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 50, 50));

        Cbrbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Cbrbutton.setText("Cbrt");
        Cbrbutton.setContentAreaFilled(false);
        Cbrbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cbrbutton.setOpaque(true);
        Cbrbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbrbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Cbrbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 100, 50));

        Roundbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Roundbutton.setText("Round");
        Roundbutton.setContentAreaFilled(false);
        Roundbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Roundbutton.setOpaque(true);
        Roundbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Roundbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 100, 50));

        Hexbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Hexbutton.setText("Hex");
        Hexbutton.setContentAreaFilled(false);
        Hexbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Hexbutton.setOpaque(true);
        Hexbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Hexbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, 50));

        Binbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Binbutton.setText("Bin");
        Binbutton.setContentAreaFilled(false);
        Binbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Binbutton.setOpaque(true);
        Binbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Binbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 70, 50));

        Modbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Modbutton.setText("Mod");
        Modbutton.setContentAreaFilled(false);
        Modbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modbutton.setOpaque(true);
        Modbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Modbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 100, 50));

        lnxbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lnxbutton.setText("lnx");
        lnxbutton.setContentAreaFilled(false);
        lnxbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lnxbutton.setOpaque(true);
        lnxbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnxbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(lnxbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 100, 50));

        Degbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Degbutton.setText("Deg");
        Degbutton.setContentAreaFilled(false);
        Degbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Degbutton.setOpaque(true);
        Degbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Degbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 100, 50));

        Radbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Radbutton.setText("Rad");
        Radbutton.setContentAreaFilled(false);
        Radbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Radbutton.setOpaque(true);
        Radbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Radbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 100, 50));

        Octalbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Octalbutton.setText("Octal");
        Octalbutton.setContentAreaFilled(false);
        Octalbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Octalbutton.setOpaque(true);
        Octalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctalbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Octalbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 100, 50));

        Calculatorlabel.setBackground(new java.awt.Color(255, 255, 255));
        Calculatorlabel.setForeground(new java.awt.Color(255, 255, 255));
        Calculatorlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calculatorlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 26.jpg"))); // NOI18N
        Calculatorlabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Calculatorlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Calculatorlabel.setOpaque(true);
        getContentPane().add(Calculatorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to Homescreen");
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Standard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Standard.setText("Standard Calculator");
        Standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardActionPerformed(evt);
            }
        });
        Filemenu.add(Standard);

        Scientific.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Scientific.setText("Scientific Calculator");
        Scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScientificActionPerformed(evt);
            }
        });
        Filemenu.add(Scientific);

        jMenuBar1.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        jMenuBar1.add(Helpmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void DividebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DividebuttonActionPerformed
firstnum = Double.parseDouble(input.getText());
input.setText(null);
operations=("/");
        // TODO add your handling code here:
    }//GEN-LAST:event_DividebuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(306, 515);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void StandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardActionPerformed
this.setResizable(true);
this.setSize(306, 515);
input.setSize(270, 60);
Separator.setSize(270, 5);
Powerpanel.setSize(290, 60);
input.setSize(270, 60);
        // TODO add your handling code here:
    }//GEN-LAST:event_StandardActionPerformed

    private void ScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScientificActionPerformed
this.setResizable(true);
this.setSize(696, 515);
input.setSize(660, 60);
Separator.setSize(660, 5);
Powerpanel.setSize(680, 60);
input.setSize(660, 60);
        // TODO add your handling code here:
    }//GEN-LAST:event_ScientificActionPerformed

    private void SevenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenbuttonActionPerformed
String iNum = input.getText()+Sevenbutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_SevenbuttonActionPerformed

    private void EightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightbuttonActionPerformed
String iNum = input.getText()+Eightbutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_EightbuttonActionPerformed

    private void NinebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NinebuttonActionPerformed
String iNum = input.getText()+Ninebutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_NinebuttonActionPerformed

    private void FourbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourbuttonActionPerformed
String iNum = input.getText()+Fourbutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_FourbuttonActionPerformed

    private void FivebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FivebuttonActionPerformed
String iNum = input.getText()+Fivebutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_FivebuttonActionPerformed

    private void SixbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixbuttonActionPerformed
String iNum = input.getText()+Sixbutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_SixbuttonActionPerformed

    private void OnebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnebuttonActionPerformed
String iNum = input.getText()+Onebutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_OnebuttonActionPerformed

    private void TwobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwobuttonActionPerformed
String iNum = input.getText()+Twobutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_TwobuttonActionPerformed

    private void ThreebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreebuttonActionPerformed
String iNum = input.getText()+Threebutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_ThreebuttonActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
String backspace = null;
if(input.getText().length() > 0)
{
    StringBuilder strB = new StringBuilder(input.getText());
    strB.deleteCharAt(input.getText().length()-1);
    backspace = strB.toString();
    input.setText(backspace);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void ZerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZerobuttonActionPerformed
String iNum = input.getText()+Zerobutton.getText();
input.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_ZerobuttonActionPerformed

    private void DotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotButtonActionPerformed
if(!input.getText().contains("."))
{
    input.setText(input.getText()+DotButton.getText());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_DotButtonActionPerformed

    private void PlusminusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusminusbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = A*(-1);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusminusbuttonActionPerformed

    private void SqrtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.sqrt(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_SqrtbuttonActionPerformed

    private void Logbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logbutton1ActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.log(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_Logbutton1ActionPerformed

    private void SinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.sin(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_SinbuttonActionPerformed

    private void SinhbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinhbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.sinh(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_SinhbuttonActionPerformed

    private void CbrbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbrbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.cbrt(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_CbrbuttonActionPerformed

    private void RoundbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.round(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_RoundbuttonActionPerformed

    private void CosbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.cos(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_CosbuttonActionPerformed

    private void CoshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoshbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.cosh(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_CoshbuttonActionPerformed

    private void TanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.tan(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_TanbuttonActionPerformed

    private void TanhbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanhbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.tanh(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_TanhbuttonActionPerformed

    private void xybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xybuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.pow(A, A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_xybuttonActionPerformed

    private void x2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2buttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = (A*A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_x2buttonActionPerformed

    private void x3buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3buttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = (A*A*A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_x3buttonActionPerformed

    private void piebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piebuttonActionPerformed
double A;
A = (3.1415936535897932384626433832795);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_piebuttonActionPerformed

    private void ACbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACbuttonActionPerformed
input.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ACbuttonActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void HexbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexbuttonActionPerformed
int A = Integer.parseInt(input.getText());
input.setText(Integer.toHexString(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_HexbuttonActionPerformed

    private void BinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinbuttonActionPerformed
int A = Integer.parseInt(input.getText());
input.setText(Integer.toBinaryString(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_BinbuttonActionPerformed

    private void EqualbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualbuttonActionPerformed
String answer;
secondnum = Double.parseDouble(input.getText());
if(operations=="+")
{
    result = firstnum+secondnum;
    answer = String.format("%.2f", result);
    input.setText(answer);
}
else if(operations=="-")
{
    result = firstnum-secondnum;
    answer = String.format("%.2f", result);
    input.setText(answer);
}
if(operations=="*")
{
    result = firstnum*secondnum;
    answer = String.format("%.2f", result);
    input.setText(answer);
}
if(operations=="/")
{
    result = firstnum/secondnum;
    answer = String.format("%.2f", result);
    input.setText(answer);
}
if(operations=="%")
{
    result = firstnum%secondnum;
    answer = String.format("%.2f", result);
    input.setText(answer);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_EqualbuttonActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
firstnum = Double.parseDouble(input.getText());
input.setText(null);
operations=("+");
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void SubtractbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractbuttonActionPerformed
firstnum = Double.parseDouble(input.getText());
input.setText(null);
operations=("-");
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtractbuttonActionPerformed

    private void MultiplybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplybuttonActionPerformed
firstnum = Double.parseDouble(input.getText());
input.setText(null);
operations=("*");
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplybuttonActionPerformed

    private void ModbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModbuttonActionPerformed
firstnum = Double.parseDouble(input.getText());
input.setText(null);
operations=("%");
        // TODO add your handling code here:
    }//GEN-LAST:event_ModbuttonActionPerformed

    private void lnxbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnxbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.log10(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_lnxbuttonActionPerformed

    private void DegbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.toDegrees(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_DegbuttonActionPerformed

    private void RadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadbuttonActionPerformed
double A = Double.parseDouble(String.valueOf(input.getText()));
A = Math.toRadians(A);
input.setText(String.valueOf(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_RadbuttonActionPerformed

    private void OctalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctalbuttonActionPerformed
int A = Integer.parseInt(input.getText());
input.setText(Integer.toOctalString(A));
        // TODO add your handling code here:
    }//GEN-LAST:event_OctalbuttonActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACbutton;
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Addbutton;
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Binbutton;
    private javax.swing.JLabel Calculatorlabel;
    private javax.swing.JButton Cbrbutton;
    private javax.swing.JButton Cosbutton;
    private javax.swing.JButton Coshbutton;
    private javax.swing.JButton Degbutton;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JButton Dividebutton;
    private javax.swing.JButton DotButton;
    private javax.swing.JButton Eightbutton;
    private javax.swing.JButton Equalbutton;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JButton Fivebutton;
    private javax.swing.JButton Fourbutton;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Hexbutton;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JButton Logbutton1;
    private javax.swing.JButton Modbutton;
    private javax.swing.JButton Multiplybutton;
    private javax.swing.JButton Ninebutton;
    private javax.swing.JButton Octalbutton;
    private javax.swing.JButton Onebutton;
    private javax.swing.JButton Plusminusbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JButton Radbutton;
    private javax.swing.JButton Roundbutton;
    private javax.swing.JMenuItem Scientific;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton Sevenbutton;
    private javax.swing.JButton Sinbutton;
    private javax.swing.JButton Sinhbutton;
    private javax.swing.JButton Sixbutton;
    private javax.swing.JButton Sqrtbutton;
    private javax.swing.JMenuItem Standard;
    private javax.swing.JButton Subtractbutton;
    private javax.swing.JButton Tanbutton;
    private javax.swing.JButton Tanhbutton;
    private javax.swing.JButton Threebutton;
    private javax.swing.JButton Twobutton;
    private javax.swing.JButton Zerobutton;
    private javax.swing.JTextField input;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton lnxbutton;
    private javax.swing.JButton piebutton;
    private javax.swing.JButton x2button;
    private javax.swing.JButton x3button;
    private javax.swing.JButton xybutton;
    // End of variables declaration//GEN-END:variables
}
