package legionnaire_os;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Change_Background extends javax.swing.JFrame {

    /**
     * Creates new form Change_Background
     */
    public Change_Background() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        homeback1 = new javax.swing.JButton();
        homeback2 = new javax.swing.JButton();
        homeback3 = new javax.swing.JButton();
        homeback4 = new javax.swing.JButton();
        homeback5 = new javax.swing.JButton();
        homeback6 = new javax.swing.JButton();
        homeback8 = new javax.swing.JButton();
        homeback9 = new javax.swing.JButton();
        homeback10 = new javax.swing.JButton();
        homeback11 = new javax.swing.JButton();
        homeback12 = new javax.swing.JButton();
        homeback13 = new javax.swing.JButton();
        homeback14 = new javax.swing.JButton();
        homeback15 = new javax.swing.JButton();
        homeback16 = new javax.swing.JButton();
        homeback17 = new javax.swing.JButton();
        homeback18 = new javax.swing.JButton();
        Loginbacklabel = new javax.swing.JLabel();
        Homebacklabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        loginback1 = new javax.swing.JButton();
        loginback2 = new javax.swing.JButton();
        loginback3 = new javax.swing.JButton();
        loginback4 = new javax.swing.JButton();
        loginback5 = new javax.swing.JButton();
        loginback6 = new javax.swing.JButton();
        loginback8 = new javax.swing.JButton();
        loginback9 = new javax.swing.JButton();
        loginback10 = new javax.swing.JButton();
        loginback11 = new javax.swing.JButton();
        loginback12 = new javax.swing.JButton();
        loginback13 = new javax.swing.JButton();
        loginback14 = new javax.swing.JButton();
        loginback15 = new javax.swing.JButton();
        loginback16 = new javax.swing.JButton();
        loginback17 = new javax.swing.JButton();
        loginback18 = new javax.swing.JButton();
        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        changebacklabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        homeback1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back1 icon.jpg"))); // NOI18N
        homeback1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback1.setContentAreaFilled(false);
        homeback1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback1MouseClicked(evt);
            }
        });

        homeback2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back2 icon.jpg"))); // NOI18N
        homeback2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback2.setContentAreaFilled(false);
        homeback2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback2MouseClicked(evt);
            }
        });

        homeback3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back3 icon.jpg"))); // NOI18N
        homeback3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback3.setContentAreaFilled(false);
        homeback3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback3MouseClicked(evt);
            }
        });

        homeback4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back4 icon.jpg"))); // NOI18N
        homeback4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback4.setContentAreaFilled(false);
        homeback4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback4MouseClicked(evt);
            }
        });

        homeback5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back5 icon.jpg"))); // NOI18N
        homeback5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback5.setContentAreaFilled(false);
        homeback5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback5MouseClicked(evt);
            }
        });

        homeback6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back6 icon.jpg"))); // NOI18N
        homeback6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback6.setContentAreaFilled(false);
        homeback6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback6MouseClicked(evt);
            }
        });

        homeback8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back8 icon.jpg"))); // NOI18N
        homeback8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback8.setContentAreaFilled(false);
        homeback8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeback8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback8MouseClicked(evt);
            }
        });

        homeback9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 9 icon.jpg"))); // NOI18N
        homeback9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 2));
        homeback9.setContentAreaFilled(false);
        homeback9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback9MouseClicked(evt);
            }
        });

        homeback10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 10 icon.jpg"))); // NOI18N
        homeback10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback10.setContentAreaFilled(false);
        homeback10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback10MouseClicked(evt);
            }
        });

        homeback11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 11 icon.jpg"))); // NOI18N
        homeback11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback11.setContentAreaFilled(false);
        homeback11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback11MouseClicked(evt);
            }
        });

        homeback12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 12 icon.jpg"))); // NOI18N
        homeback12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback12.setContentAreaFilled(false);
        homeback12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback12MouseClicked(evt);
            }
        });

        homeback13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 13 icon.jpg"))); // NOI18N
        homeback13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback13.setContentAreaFilled(false);
        homeback13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback13MouseClicked(evt);
            }
        });

        homeback14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 14 icon.jpg"))); // NOI18N
        homeback14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback14.setContentAreaFilled(false);
        homeback14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback14MouseClicked(evt);
            }
        });

        homeback15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 15 icon.jpg"))); // NOI18N
        homeback15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback15.setContentAreaFilled(false);
        homeback15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback15MouseClicked(evt);
            }
        });

        homeback16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 16 icon.jpg"))); // NOI18N
        homeback16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback16.setContentAreaFilled(false);
        homeback16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback16MouseClicked(evt);
            }
        });

        homeback17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 17 icon.jpg"))); // NOI18N
        homeback17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback17.setContentAreaFilled(false);
        homeback17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback17MouseClicked(evt);
            }
        });

        homeback18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 18 icon.jpg"))); // NOI18N
        homeback18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        homeback18.setContentAreaFilled(false);
        homeback18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeback18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeback1)
                .addGap(18, 18, 18)
                .addComponent(homeback2)
                .addGap(18, 18, 18)
                .addComponent(homeback3)
                .addGap(18, 18, 18)
                .addComponent(homeback4)
                .addGap(18, 18, 18)
                .addComponent(homeback5)
                .addGap(18, 18, 18)
                .addComponent(homeback6)
                .addGap(18, 18, 18)
                .addComponent(homeback8)
                .addGap(18, 18, 18)
                .addComponent(homeback9)
                .addGap(18, 18, 18)
                .addComponent(homeback10)
                .addGap(18, 18, 18)
                .addComponent(homeback11)
                .addGap(18, 18, 18)
                .addComponent(homeback12)
                .addGap(18, 18, 18)
                .addComponent(homeback13)
                .addGap(18, 18, 18)
                .addComponent(homeback14)
                .addGap(18, 18, 18)
                .addComponent(homeback15)
                .addGap(18, 18, 18)
                .addComponent(homeback16)
                .addGap(18, 18, 18)
                .addComponent(homeback17)
                .addGap(18, 18, 18)
                .addComponent(homeback18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeback15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(homeback18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeback9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(homeback10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 980, 210));

        Loginbacklabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Loginbacklabel.setForeground(new java.awt.Color(102, 255, 255));
        Loginbacklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginbacklabel.setText("Change Login Screen Background");
        getContentPane().add(Loginbacklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        Homebacklabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Homebacklabel.setForeground(new java.awt.Color(102, 255, 255));
        Homebacklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homebacklabel.setText("Change Home Screen Background");
        getContentPane().add(Homebacklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        loginback1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back1 icon.jpg"))); // NOI18N
        loginback1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback1.setContentAreaFilled(false);
        loginback1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback1MouseClicked(evt);
            }
        });

        loginback2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back2 icon.jpg"))); // NOI18N
        loginback2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback2.setContentAreaFilled(false);
        loginback2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback2MouseClicked(evt);
            }
        });

        loginback3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back3 icon.jpg"))); // NOI18N
        loginback3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback3.setContentAreaFilled(false);
        loginback3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback3MouseClicked(evt);
            }
        });

        loginback4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back4 icon.jpg"))); // NOI18N
        loginback4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback4.setContentAreaFilled(false);
        loginback4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback4MouseClicked(evt);
            }
        });

        loginback5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back5 icon.jpg"))); // NOI18N
        loginback5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback5.setContentAreaFilled(false);
        loginback5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback5MouseClicked(evt);
            }
        });

        loginback6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back6 icon.jpg"))); // NOI18N
        loginback6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback6.setContentAreaFilled(false);
        loginback6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback6MouseClicked(evt);
            }
        });

        loginback8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back8 icon.jpg"))); // NOI18N
        loginback8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback8.setContentAreaFilled(false);
        loginback8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginback8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback8MouseClicked(evt);
            }
        });

        loginback9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 9 icon.jpg"))); // NOI18N
        loginback9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback9.setContentAreaFilled(false);
        loginback9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback9MouseClicked(evt);
            }
        });

        loginback10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 10 icon.jpg"))); // NOI18N
        loginback10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback10.setContentAreaFilled(false);
        loginback10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback10MouseClicked(evt);
            }
        });

        loginback11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 11 icon.jpg"))); // NOI18N
        loginback11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback11.setContentAreaFilled(false);
        loginback11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback11MouseClicked(evt);
            }
        });

        loginback12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 12 icon.jpg"))); // NOI18N
        loginback12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback12.setContentAreaFilled(false);
        loginback12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback12MouseClicked(evt);
            }
        });

        loginback13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 13 icon.jpg"))); // NOI18N
        loginback13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback13.setContentAreaFilled(false);
        loginback13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback13MouseClicked(evt);
            }
        });

        loginback14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 14 icon.jpg"))); // NOI18N
        loginback14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback14.setContentAreaFilled(false);
        loginback14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback14MouseClicked(evt);
            }
        });

        loginback15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 15 icon.jpg"))); // NOI18N
        loginback15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback15.setContentAreaFilled(false);
        loginback15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback15MouseClicked(evt);
            }
        });

        loginback16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 16 icon.jpg"))); // NOI18N
        loginback16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback16.setContentAreaFilled(false);
        loginback16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback16MouseClicked(evt);
            }
        });

        loginback17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 17 icon.jpg"))); // NOI18N
        loginback17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback17.setContentAreaFilled(false);
        loginback17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback17MouseClicked(evt);
            }
        });

        loginback18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 18 icon.jpg"))); // NOI18N
        loginback18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        loginback18.setContentAreaFilled(false);
        loginback18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginback18MouseClicked(evt);
            }
        });
        loginback18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginback18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginback1)
                .addGap(18, 18, 18)
                .addComponent(loginback2)
                .addGap(18, 18, 18)
                .addComponent(loginback3)
                .addGap(18, 18, 18)
                .addComponent(loginback4)
                .addGap(18, 18, 18)
                .addComponent(loginback5)
                .addGap(18, 18, 18)
                .addComponent(loginback6)
                .addGap(18, 18, 18)
                .addComponent(loginback8)
                .addGap(18, 18, 18)
                .addComponent(loginback9)
                .addGap(18, 18, 18)
                .addComponent(loginback10)
                .addGap(18, 18, 18)
                .addComponent(loginback11)
                .addGap(18, 18, 18)
                .addComponent(loginback12)
                .addGap(18, 18, 18)
                .addComponent(loginback13)
                .addGap(18, 18, 18)
                .addComponent(loginback14)
                .addGap(18, 18, 18)
                .addComponent(loginback15)
                .addGap(18, 18, 18)
                .addComponent(loginback16)
                .addGap(18, 18, 18)
                .addComponent(loginback17)
                .addGap(18, 18, 18)
                .addComponent(loginback18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginback18, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loginback4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(loginback3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginback2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginback1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginback6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginback8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginback9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(loginback5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(loginback11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback14, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback16, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginback17, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 980, 210));

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 60));

        changebacklabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 19.jpg"))); // NOI18N
        getContentPane().add(changebacklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Setting_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1025, 707);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void homeback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback1MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back1.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback1MouseClicked

    private void homeback2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback2MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back2.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback2MouseClicked

    private void homeback3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback3MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back3.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback3MouseClicked

    private void homeback4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback4MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back4.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback4MouseClicked

    private void homeback5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback5MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back5.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback5MouseClicked

    private void homeback6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback6MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back6.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback6MouseClicked

    private void homeback8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback8MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back8.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback8MouseClicked

    private void homeback9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback9MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back9.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback9MouseClicked

    private void homeback10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback10MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back10.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback10MouseClicked

    private void homeback11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback11MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back11.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback11MouseClicked

    private void homeback12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback12MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back12.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback12MouseClicked

    private void homeback13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback13MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back13.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback13MouseClicked

    private void homeback14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback14MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back14.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback14MouseClicked

    private void homeback15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback15MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back15.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback15MouseClicked

    private void homeback16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback16MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back16.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback16MouseClicked

    private void homeback17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback17MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back17.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback17MouseClicked

    private void homeback18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeback18MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set homescreen='back18.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_homeback18MouseClicked

    private void loginback18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginback18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback18ActionPerformed

    private void loginback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback1MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back1.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback1MouseClicked

    private void loginback2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback2MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back2.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback2MouseClicked

    private void loginback3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback3MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back3.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback3MouseClicked

    private void loginback4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback4MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back4.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback4MouseClicked

    private void loginback5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback5MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back5.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback5MouseClicked

    private void loginback6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback6MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back6.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback6MouseClicked

    private void loginback8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback8MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back8.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback8MouseClicked

    private void loginback9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback9MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back9.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback9MouseClicked

    private void loginback10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback10MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back10.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback10MouseClicked

    private void loginback11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback11MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back11.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback11MouseClicked

    private void loginback12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback12MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back12.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback12MouseClicked

    private void loginback13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback13MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back13.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback13MouseClicked

    private void loginback14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback14MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back14.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback14MouseClicked

    private void loginback15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback15MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back15.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback15MouseClicked

    private void loginback16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback16MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back16.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback16MouseClicked

    private void loginback17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback17MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back17.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback17MouseClicked

    private void loginback18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginback18MouseClicked
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Update backgrounds set loginscreen='back18.jpg';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Background set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginback18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Change_Background().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Backbutton;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JLabel Homebacklabel;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JLabel Loginbacklabel;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JLabel changebacklabel;
    public javax.swing.JButton homeback1;
    public javax.swing.JButton homeback10;
    public javax.swing.JButton homeback11;
    public javax.swing.JButton homeback12;
    public javax.swing.JButton homeback13;
    public javax.swing.JButton homeback14;
    public javax.swing.JButton homeback15;
    public javax.swing.JButton homeback16;
    public javax.swing.JButton homeback17;
    public javax.swing.JButton homeback18;
    public javax.swing.JButton homeback2;
    public javax.swing.JButton homeback3;
    public javax.swing.JButton homeback4;
    public javax.swing.JButton homeback5;
    public javax.swing.JButton homeback6;
    public javax.swing.JButton homeback8;
    public javax.swing.JButton homeback9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton loginback1;
    public javax.swing.JButton loginback10;
    public javax.swing.JButton loginback11;
    public javax.swing.JButton loginback12;
    public javax.swing.JButton loginback13;
    public javax.swing.JButton loginback14;
    public javax.swing.JButton loginback15;
    public javax.swing.JButton loginback16;
    public javax.swing.JButton loginback17;
    public javax.swing.JButton loginback18;
    public javax.swing.JButton loginback2;
    public javax.swing.JButton loginback3;
    public javax.swing.JButton loginback4;
    public javax.swing.JButton loginback5;
    public javax.swing.JButton loginback6;
    public javax.swing.JButton loginback8;
    public javax.swing.JButton loginback9;
    // End of variables declaration//GEN-END:variables
}
