package legionnaire_os;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Change_Avatar extends javax.swing.JFrame {

    /**
     * Creates new form Change_Avatar
     */
    public Change_Avatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        user1button = new javax.swing.JButton();
        user2button = new javax.swing.JButton();
        user3button = new javax.swing.JButton();
        user4button = new javax.swing.JButton();
        user5button = new javax.swing.JButton();
        user6button = new javax.swing.JButton();
        user7button = new javax.swing.JButton();
        user8button = new javax.swing.JButton();
        user9button = new javax.swing.JButton();
        user10button = new javax.swing.JButton();
        user11button = new javax.swing.JButton();
        user12button = new javax.swing.JButton();
        user13button = new javax.swing.JButton();
        user14button = new javax.swing.JButton();
        user15button = new javax.swing.JButton();
        changeavatarlabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 60));

        user1button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user1.png"))); // NOI18N
        user1button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user1button.setContentAreaFilled(false);
        user1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        user2button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user2.png"))); // NOI18N
        user2button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user2button.setContentAreaFilled(false);
        user2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        user3button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user3.png"))); // NOI18N
        user3button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user3button.setContentAreaFilled(false);
        user3button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user3buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user3button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        user4button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user4.png"))); // NOI18N
        user4button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user4button.setContentAreaFilled(false);
        user4button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user4buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user4button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        user5button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user5.png"))); // NOI18N
        user5button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user5button.setContentAreaFilled(false);
        user5button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user5buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user5button, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        user6button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user6.png"))); // NOI18N
        user6button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user6button.setContentAreaFilled(false);
        user6button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user6buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user6button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        user7button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user7.png"))); // NOI18N
        user7button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user7button.setContentAreaFilled(false);
        user7button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user7buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user7button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        user8button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user8.png"))); // NOI18N
        user8button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user8button.setContentAreaFilled(false);
        user8button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user8buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user8button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        user9button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user9.png"))); // NOI18N
        user9button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user9button.setContentAreaFilled(false);
        user9button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user9buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user9button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        user10button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user10.png"))); // NOI18N
        user10button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user10button.setContentAreaFilled(false);
        user10button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user10buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user10button, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));

        user11button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user11.png"))); // NOI18N
        user11button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user11button.setContentAreaFilled(false);
        user11button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user11buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user11button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        user12button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user12.png"))); // NOI18N
        user12button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user12button.setContentAreaFilled(false);
        user12button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user12buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user12button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        user13button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user13.png"))); // NOI18N
        user13button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user13button.setContentAreaFilled(false);
        user13button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user13buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user13button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        user14button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user14.png"))); // NOI18N
        user14button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user14button.setContentAreaFilled(false);
        user14button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user14buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user14button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        user15button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user15.png"))); // NOI18N
        user15button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        user15button.setContentAreaFilled(false);
        user15button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user15buttonActionPerformed(evt);
            }
        });
        getContentPane().add(user15button, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));

        changeavatarlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back 19.jpg"))); // NOI18N
        getContentPane().add(changeavatarlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.setOpaque(true);
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Setting_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1025, 707);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void user1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user1.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user1buttonActionPerformed

    private void user2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user2.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user2buttonActionPerformed

    private void user3buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user3buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user3.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user3buttonActionPerformed

    private void user4buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user4buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user4.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user4buttonActionPerformed

    private void user5buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user5buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user5.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user5buttonActionPerformed

    private void user6buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user6buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user6.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user6buttonActionPerformed

    private void user7buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user7buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user7.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user7buttonActionPerformed

    private void user8buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user8buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user8.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user8buttonActionPerformed

    private void user9buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user9buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user9.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user9buttonActionPerformed

    private void user10buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user10buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user10.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user10buttonActionPerformed

    private void user11buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user11buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user11.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user11buttonActionPerformed

    private void user12buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user12buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user12.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user12buttonActionPerformed

    private void user13buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user13buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user13.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user13buttonActionPerformed

    private void user14buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user14buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user14.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user14buttonActionPerformed

    private void user15buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user15buttonActionPerformed
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "UPDATE UserAvatar SET avatar='user15.png';";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Avatar set successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_user15buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Avatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Backbutton;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JLabel changeavatarlabel;
    public javax.swing.JButton user10button;
    public javax.swing.JButton user11button;
    public javax.swing.JButton user12button;
    public javax.swing.JButton user13button;
    public javax.swing.JButton user14button;
    public javax.swing.JButton user15button;
    public javax.swing.JButton user1button;
    public javax.swing.JButton user2button;
    public javax.swing.JButton user3button;
    public javax.swing.JButton user4button;
    public javax.swing.JButton user5button;
    public javax.swing.JButton user6button;
    public javax.swing.JButton user7button;
    public javax.swing.JButton user8button;
    public javax.swing.JButton user9button;
    // End of variables declaration//GEN-END:variables
}
