package legionnaire_os;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
import java.math.BigInteger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Contacts_App extends javax.swing.JFrame {

    /**
     * Creates new form Contacts_App
     */
    public Contacts_App() {
        initComponents();

//---------------------Contacts display in table--------------------//
    DefaultTableModel model = (DefaultTableModel)
    Contacttable.getModel();
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid","root", "mandy15012001");
            Statement stmt = con.createStatement();
            String query="SELECT * FROM contacts;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
            String SrNo = rs.getString("Sr_No");
            String FirstName = rs.getString("First_Name");
            String LastName = rs.getString("Last_Name");
            String Number = rs.getString("Number");
            model.addRow (new Object[] {SrNo, FirstName, LastName,Number});
            }
        }
    catch (Exception e)
        {
            JOptionPane.showMessageDialog (this, "Error in Connectivity!");
        }

//-----------------name display in recent called-------------------//
    try 
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM calling";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) 
                {
                    String Name = rs.getString(1);
                    String Number = rs.getString(2);
                    Contactname.setText(""+Name);
                    Contactnumber.setText("" +Number);
                }
            
            con.close();
            stmt.close();
            rs.close();
        } 
    catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error in Connectivity!");
        }
    }

/**********************************************************************************************************/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Searchbutton = new javax.swing.JButton();
        Recentpanel = new javax.swing.JPanel();
        Recent = new javax.swing.JLabel();
        Contacticon = new javax.swing.JLabel();
        Contactnumber = new javax.swing.JLabel();
        Contactname = new javax.swing.JLabel();
        Callbackbutton = new javax.swing.JButton();
        Searchtext = new javax.swing.JTextField();
        Tabs = new javax.swing.JTabbedPane();
        Contactstab = new javax.swing.JScrollPane();
        Contacttable = new javax.swing.JTable();
        Addcontacttab = new javax.swing.JPanel();
        Addcontactlabel = new javax.swing.JLabel();
        firstlabel = new javax.swing.JLabel();
        lastlabel = new javax.swing.JLabel();
        numberlabel = new javax.swing.JLabel();
        Addcontactbutton = new javax.swing.JButton();
        firsttext = new javax.swing.JTextField();
        lasttext = new javax.swing.JTextField();
        numbertext = new javax.swing.JTextField();
        Updatetab = new javax.swing.JPanel();
        srlabel = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        last = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        firstTF = new javax.swing.JTextField();
        lastTF = new javax.swing.JTextField();
        numberTF = new javax.swing.JTextField();
        Deletebutton = new javax.swing.JButton();
        Updatebutton = new javax.swing.JButton();
        Resetbutton = new javax.swing.JButton();
        Showdetailbutton = new javax.swing.JButton();
        Srenter = new javax.swing.JTextField();
        Powerpanel = new javax.swing.JPanel();
        Powerbutton = new javax.swing.JButton();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Contactbacklabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JCheckBoxMenuItem();
        JumpAppmenu = new javax.swing.JCheckBoxMenuItem();
        ExitOSmenu = new javax.swing.JCheckBoxMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Searchbutton.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Searchbutton.setForeground(new java.awt.Color(0, 255, 255));
        Searchbutton.setText("Search");
        Searchbutton.setContentAreaFilled(false);
        Searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbutton);
        Searchbutton.setBounds(460, 20, 140, 40);

        Recentpanel.setOpaque(false);

        Recent.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Recent.setForeground(new java.awt.Color(0, 255, 255));
        Recent.setText("Recent -");

        Contacticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/contact user icon.png"))); // NOI18N

        Contactnumber.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Contactnumber.setForeground(new java.awt.Color(0, 255, 255));

        Contactname.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Contactname.setForeground(new java.awt.Color(0, 255, 255));

        Callbackbutton.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Callbackbutton.setForeground(new java.awt.Color(255, 255, 255));
        Callbackbutton.setText("Call Back");
        Callbackbutton.setContentAreaFilled(false);
        Callbackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallbackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RecentpanelLayout = new javax.swing.GroupLayout(Recentpanel);
        Recentpanel.setLayout(RecentpanelLayout);
        RecentpanelLayout.setHorizontalGroup(
            RecentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecentpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contacticon)
                .addGroup(RecentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecentpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Contactname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecentpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Contactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(Callbackbutton)
                .addContainerGap())
            .addGroup(RecentpanelLayout.createSequentialGroup()
                .addComponent(Recent)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RecentpanelLayout.setVerticalGroup(
            RecentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecentpanelLayout.createSequentialGroup()
                .addComponent(Recent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RecentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contacticon)
                    .addGroup(RecentpanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(RecentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Callbackbutton)
                            .addGroup(RecentpanelLayout.createSequentialGroup()
                                .addComponent(Contactname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Contactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Recentpanel);
        Recentpanel.setBounds(30, 70, 560, 130);

        Searchtext.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Searchtext.setForeground(new java.awt.Color(0, 255, 255));
        Searchtext.setText(" Search by First Name.....");
        Searchtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Searchtext.setOpaque(false);
        Searchtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchtextMouseClicked(evt);
            }
        });
        getContentPane().add(Searchtext);
        Searchtext.setBounds(20, 20, 420, 40);

        Tabs.setBackground(new java.awt.Color(204, 204, 255));
        Tabs.setToolTipText("");
        Tabs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabsMouseClicked(evt);
            }
        });

        Contacttable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        Contacttable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Contacttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No", "First Name", "Last Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Contactstab.setViewportView(Contacttable);

        Tabs.addTab("Contacts", Contactstab);

        Addcontacttab.setBackground(new java.awt.Color(204, 204, 255));

        Addcontactlabel.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        Addcontactlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Addcontactlabel.setText("Add a Contact");
        Addcontactlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        firstlabel.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        firstlabel.setText("Enter First Name");

        lastlabel.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        lastlabel.setText("Enter Last Name");

        numberlabel.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        numberlabel.setText("Enter the Number");

        Addcontactbutton.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Addcontactbutton.setForeground(new java.awt.Color(102, 102, 255));
        Addcontactbutton.setText("Add Contact");
        Addcontactbutton.setContentAreaFilled(false);
        Addcontactbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddcontactbuttonActionPerformed(evt);
            }
        });

        firsttext.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        firsttext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lasttext.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        lasttext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        numbertext.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        numbertext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout AddcontacttabLayout = new javax.swing.GroupLayout(Addcontacttab);
        Addcontacttab.setLayout(AddcontacttabLayout);
        AddcontacttabLayout.setHorizontalGroup(
            AddcontacttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddcontacttabLayout.createSequentialGroup()
                .addGroup(AddcontacttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddcontacttabLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(AddcontacttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastlabel)
                            .addComponent(firstlabel)
                            .addComponent(numberlabel))
                        .addGap(44, 44, 44)
                        .addGroup(AddcontacttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firsttext, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(lasttext)
                            .addComponent(numbertext))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(AddcontacttabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Addcontactlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(AddcontacttabLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(Addcontactbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddcontacttabLayout.setVerticalGroup(
            AddcontacttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddcontacttabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Addcontactlabel)
                .addGap(29, 29, 29)
                .addGroup(AddcontacttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddcontacttabLayout.createSequentialGroup()
                        .addComponent(firstlabel)
                        .addGap(22, 22, 22)
                        .addComponent(lastlabel)
                        .addGap(27, 27, 27)
                        .addComponent(numberlabel))
                    .addGroup(AddcontacttabLayout.createSequentialGroup()
                        .addComponent(firsttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lasttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(numbertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Addcontactbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabs.addTab("Add a Contact", Addcontacttab);

        Updatetab.setBackground(new java.awt.Color(204, 204, 255));

        srlabel.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        srlabel.setText("Enter Sr No. (You can check from Contacts)");

        first.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        first.setText("First Name");

        last.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        last.setText("Last Name");

        number.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        number.setText("Phone Number");

        firstTF.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N

        lastTF.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N

        numberTF.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N

        Deletebutton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        Deletebutton.setText("Delete");
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });

        Updatebutton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        Updatebutton.setText("Update");
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });

        Resetbutton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });

        Showdetailbutton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        Showdetailbutton.setText("Show Details");
        Showdetailbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowdetailbuttonActionPerformed(evt);
            }
        });

        Srenter.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        Srenter.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout UpdatetabLayout = new javax.swing.GroupLayout(Updatetab);
        Updatetab.setLayout(UpdatetabLayout);
        UpdatetabLayout.setHorizontalGroup(
            UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatetabLayout.createSequentialGroup()
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatetabLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(srlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Srenter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdatetabLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(Showdetailbutton))
                    .addGroup(UpdatetabLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first)
                            .addComponent(number)
                            .addComponent(last))
                        .addGap(64, 64, 64)
                        .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lastTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addGroup(UpdatetabLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatetabLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(Updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(Resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdatetabLayout.setVerticalGroup(
            UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatetabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Srenter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(srlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Showdetailbutton)
                .addGap(18, 18, 18)
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(first)
                    .addGroup(UpdatetabLayout.createSequentialGroup()
                        .addComponent(firstTF)
                        .addGap(5, 5, 5)))
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number))
                .addGap(26, 26, 26)
                .addGroup(UpdatetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletebutton)
                    .addComponent(Updatebutton)
                    .addComponent(Resetbutton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Tabs.addTab("Update Phonebook", Updatetab);

        getContentPane().add(Tabs);
        Tabs.setBounds(30, 210, 560, 360);

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Powerbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mandeep\\Documents\\IP Project Mandeep, Ajay\\ManDroidOSsim\\src\\power-xxl (1).png")); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mandeep\\Documents\\IP Project Mandeep, Ajay\\ManDroidOSsim\\src\\home-home-icon-90085 (2).png")); // NOI18N
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mandeep\\Documents\\IP Project Mandeep, Ajay\\ManDroidOSsim\\src\\android-system-back (2).png")); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Powerbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(Backbutton)
                .addContainerGap())
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel);
        Powerpanel.setBounds(0, 590, 620, 60);

        Contactbacklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contactbacklabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/contact back2.jpg"))); // NOI18N
        getContentPane().add(Contactbacklabel);
        Contactbacklabel.setBounds(0, 0, 620, 650);

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to Homescreen");
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        jMenuBar1.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Helpmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpmenuActionPerformed(evt);
            }
        });

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        jMenuBar1.add(Helpmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void AddcontactbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddcontactbuttonActionPerformed
String first = firsttext.getText();
String last = lasttext.getText();
BigInteger num = new BigInteger(numbertext.getText());
try 
{
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Mandroid", "root", "mandy15012001");
    Statement stmt = con.createStatement();
    String query = "Select max(Sr_No) from contacts";
    ResultSet rs1 = stmt.executeQuery(query);
    rs1.next();
    int srno = rs1.getInt(1) + 1;
    String query2 = "Insert into contacts values(" + srno + ",'" + first + "','" + last + "'," + num + ")";
    stmt.executeUpdate(query2);
    JOptionPane.showMessageDialog(this, "Your Contact has been added successfully", "Contact Added", JOptionPane.INFORMATION_MESSAGE);
    firsttext.setText("");
    lasttext.setText("");
    numbertext.setText("");
}
catch (Exception e) 
{
    JOptionPane.showMessageDialog(this, "Error in Connectivity!");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_AddcontactbuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(638, 715);
//setting buttons transparent
first.setVisible(false);
last.setVisible(false);
number.setVisible(false);
firstTF.setVisible(false);
lastTF.setVisible(false);
numberTF.setVisible(false);
Deletebutton.setVisible(false);
Updatebutton.setVisible(false);
Resetbutton.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void HelpmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpmenuActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
int SrNo = Integer.parseInt(Srenter.getText());
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid","root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query="DELETE FROM Contacts where Sr_no = "+SrNo+";";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog (this, "Contact Deleted Successfully.");
        Srenter.setText("");
        firstTF.setText("");
        lastTF.setText("");
        numberTF.setText("");
    }
catch(Exception e)
{
    JOptionPane.showMessageDialog (this, "Error in Connectivity!");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void ShowdetailbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowdetailbuttonActionPerformed
String SrNo = Srenter.getText();
if(SrNo.equals(""))
{
    JOptionPane.showMessageDialog(this, "Please enter Serial Number");
}
else
{
    try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "SELECT * FROM contacts where Sr_No = "+SrNo+";";
        ResultSet rs = stmt.executeQuery(query);
        while (rs.next()) 
            {
                String firstname = rs.getString(2);
                String lastname = rs.getString(3);
                String number = rs.getString(4);
                firstTF.setText(""+firstname);
                lastTF.setText("" +lastname);
                numberTF.setText(""+number);
            }
        con.close();
        stmt.close();
        rs.close();
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog (this, "Error in Connectivity!");
    }
}
first.setVisible(true);
last.setVisible(true);
number.setVisible(true);
firstTF.setVisible(true);
lastTF.setVisible(true);
numberTF.setVisible(true);
Deletebutton.setVisible(true);
Updatebutton.setVisible(true);
Resetbutton.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowdetailbuttonActionPerformed

    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbuttonActionPerformed
Srenter.setText("");
firstTF.setText("");
lastTF.setText("");
numberTF.setText("");
first.setVisible(false);
last.setVisible(false);
number.setVisible(false);
firstTF.setVisible(false);
lastTF.setVisible(false);
numberTF.setVisible(false);
Deletebutton.setVisible(false);
Updatebutton.setVisible(false);
Resetbutton.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetbuttonActionPerformed

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
String SrNo = Srenter.getText();
String First = firstTF.getText();
String Last = lastTF.getText();
String Number = numberTF.getText();
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = (Connection)
        DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = ("UPDATE Contacts SET First_Name ='"+First+"', Last_Name ='"+Last+"', Number = "+Number+" where Sr_No = "+SrNo+" ;");
        ResultSet rs = stmt.executeQuery(query);
        con.close();
        stmt.close();
        rs.close();
    } 
catch (Exception e)
    {
        JOptionPane.showMessageDialog (this, "Error in Connectivity!");
    }

DefaultTableModel model = (DefaultTableModel)
Contacttable.getModel(); int rows=model.getRowCount();
if (rows>0)
    {
        for (int i=0; i<rows; i++)
        model.removeRow(0);
    }

try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)
        DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid","root", "mandy15012001");
        Statement stmt = (Statement) con.createStatement();
        String query="SELECT * FROM Contacts;";
        ResultSet rs = stmt.executeQuery(query);
        while(rs.next())
        {
            String Name = rs.getString("Name");
            String Mobile = rs.getString("Mobile");
            String Email = rs.getString("Email");
            model.addRow (new Object[] {Name, Mobile,Email});
        }
    }
catch (Exception e)
    {
        JOptionPane.showMessageDialog (this, "Error in Connectivity!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonActionPerformed

    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbuttonActionPerformed
String Search = Searchtext.getText();
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid","root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "INSERT INTO Search VALUES('"+Search+"');";
        stmt.executeUpdate(query);
        new Contact_Details().setVisible(true);
        this.setVisible(false);
    }
catch(Exception e)
    {
        JOptionPane.showMessageDialog (this, "Error in Connectivity!");
    }
// TODO add your handling code here:

    }//GEN-LAST:event_SearchbuttonActionPerformed

    private void SearchtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchtextMouseClicked
Searchtext.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchtextMouseClicked

    private void CallbackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallbackbuttonActionPerformed
JOptionPane.showMessageDialog(this, "Sorry You have no SIM card in phone. Please insert a SIM to call");
        // TODO add your handling code here:
    }//GEN-LAST:event_CallbackbuttonActionPerformed

    private void TabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabsMouseClicked
DefaultTableModel model = (DefaultTableModel)
Contacttable.getModel(); int rows=model.getRowCount();
if (rows>0)
    {
        for (int i=0; i<rows; i++)
        model.removeRow(0);
    }
//----------------------------------------------------------//
Contacttable.getModel();
try
{
    Class.forName("java.sql.DriverManager");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid","root", "mandy15012001");
    Statement stmt = con.createStatement();
    String query="SELECT * FROM contacts;";
    ResultSet rs = stmt.executeQuery(query);
    while(rs.next())
    {
        String SrNo = rs.getString("Sr_No");
        String FirstName = rs.getString("First_Name");
        String LastName = rs.getString("Last_Name");
        String Number = rs.getString("Number");
        model.addRow (new Object[] {SrNo, FirstName, LastName,Number});
    }
}
catch (Exception e)
{
    JOptionPane.showMessageDialog (this, "Error in Connectivity!");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_TabsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contacts_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contacts_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contacts_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contacts_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contacts_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Addcontactbutton;
    private javax.swing.JLabel Addcontactlabel;
    private javax.swing.JPanel Addcontacttab;
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Callbackbutton;
    private javax.swing.JLabel Contactbacklabel;
    private javax.swing.JLabel Contacticon;
    private javax.swing.JLabel Contactname;
    private javax.swing.JLabel Contactnumber;
    private javax.swing.JScrollPane Contactstab;
    private javax.swing.JTable Contacttable;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JCheckBoxMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    private javax.swing.JCheckBoxMenuItem JumpAppmenu;
    private javax.swing.JCheckBoxMenuItem JumpHomemenu;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JLabel Recent;
    private javax.swing.JPanel Recentpanel;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JButton Searchbutton;
    public javax.swing.JTextField Searchtext;
    private javax.swing.JButton Showdetailbutton;
    private javax.swing.JTextField Srenter;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JPanel Updatetab;
    private javax.swing.JLabel first;
    private javax.swing.JTextField firstTF;
    private javax.swing.JLabel firstlabel;
    private javax.swing.JTextField firsttext;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel last;
    private javax.swing.JTextField lastTF;
    private javax.swing.JLabel lastlabel;
    private javax.swing.JTextField lasttext;
    private javax.swing.JLabel number;
    private javax.swing.JTextField numberTF;
    private javax.swing.JLabel numberlabel;
    private javax.swing.JTextField numbertext;
    private javax.swing.JLabel srlabel;
    // End of variables declaration//GEN-END:variables
}
