package legionnaire_os;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class GrizzlyBear_Login extends javax.swing.JFrame {

String curusername;
String curpassword;
    /**
     * Creates new form GrizzyBear_User_Login_Page
     */
    public GrizzlyBear_Login() {
        initComponents();

//---------------------JDBC part getting username and password--------------------//
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Select * from userpass";
        ResultSet rs = stmt.executeQuery(query);
        if (rs.first()) 
            {
                curusername = rs.getString(1);
                curpassword = rs.getString(2);
            }
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
/**********************************************************************************************************/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrizzlyBearLogo = new javax.swing.JLabel();
        GrizzlyBear = new javax.swing.JLabel();
        Usernamelabel = new javax.swing.JLabel();
        Passwordlabel = new javax.swing.JLabel();
        Usernametext = new javax.swing.JTextField();
        Loginbutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        GrizzlyBearlabel = new javax.swing.JLabel();
        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton1 = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GrizzlyBearLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GrizzlyBearLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/grizzy bear.png"))); // NOI18N
        getContentPane().add(GrizzlyBearLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 220));

        GrizzlyBear.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        GrizzlyBear.setForeground(new java.awt.Color(255, 255, 255));
        GrizzlyBear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GrizzlyBear.setText("Grizzly Bear User Login");
        getContentPane().add(GrizzlyBear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 400, 60));

        Usernamelabel.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Usernamelabel.setText("Enter Your Username");
        getContentPane().add(Usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        Passwordlabel.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Passwordlabel.setText("Enter Your Password");
        getContentPane().add(Passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        Usernametext.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Usernametext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usernametext.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                UsernametextCaretUpdate(evt);
            }
        });
        getContentPane().add(Usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 280, -1));

        Loginbutton.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Loginbutton.setText("Login");
        Loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 240, -1));

        Backbutton.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 240, -1));

        Password.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        Password.setForeground(java.awt.Color.red);
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setText("Password");
        Password.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                PasswordCaretUpdate(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 280, 40));

        GrizzlyBearlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/app back1.jpg"))); // NOI18N
        getContentPane().add(GrizzlyBearlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton1.setContentAreaFilled(false);
        Backbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backbutton1ActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton1)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 60));

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.setOpaque(true);
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Backbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backbutton1ActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Backbutton1ActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1025, 706);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void LoginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbuttonActionPerformed
String user = Usernametext.getText();
String pass = new String(Password.getPassword());
if(user.isEmpty() || pass.isEmpty())
{
    JOptionPane.showMessageDialog(this, "Fields can't be Empty!", "Caution", JOptionPane.WARNING_MESSAGE);
}
else
{
    if (user.equalsIgnoreCase(curusername) && pass.equalsIgnoreCase(curpassword)) 
    {
        JOptionPane.showMessageDialog(this,"You have been successfully logged in." );
        new GrizzlyBear_Menu().setVisible(true);
        this.dispose();
    } 
    else 
    {
        JOptionPane.showMessageDialog(this, "Password and User ID do not match. Please try again.", "Incorrect username or password", JOptionPane.ERROR_MESSAGE);
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginbuttonActionPerformed

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
Password.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordMouseClicked

    private void UsernametextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_UsernametextCaretUpdate
String user = Usernametext.getText();
if(user.equalsIgnoreCase(curusername))
{
    Usernametext.setForeground(Color.GREEN);
}
else
{
    Usernametext.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametextCaretUpdate

    private void PasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_PasswordCaretUpdate
String pass = new String(Password.getPassword());
if(pass.equalsIgnoreCase(curpassword))
{
    Password.setForeground(Color.GREEN);
}
else
{
    Password.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrizzlyBear_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrizzlyBear_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrizzlyBear_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrizzlyBear_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrizzlyBear_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Backbutton1;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JLabel GrizzlyBear;
    private javax.swing.JLabel GrizzlyBearLogo;
    private javax.swing.JLabel GrizzlyBearlabel;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JButton Loginbutton;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Passwordlabel;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JLabel Usernamelabel;
    private javax.swing.JTextField Usernametext;
    // End of variables declaration//GEN-END:variables
}
