package legionnaire_os;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
//---------------------JDBC part getting background--------------------------------//
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "SELECT * from Backgrounds";
        ResultSet rs = stmt.executeQuery(query);
        if (rs.first()) 
        {
            String homebackg = rs.getString(1);
            Homelabel.setIcon(new ImageIcon(getClass().getResource(homebackg)));
        }
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(null, "Error in Connectivity!");
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LegionaireOSlabel = new javax.swing.JLabel();
        Menubutton = new javax.swing.JButton();
        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        GrizzlyBearbutton = new javax.swing.JButton();
        Calculatorbutton = new javax.swing.JButton();
        Contactsbutton = new javax.swing.JButton();
        BullsandCowsbutton = new javax.swing.JButton();
        BullsandCowslabel = new javax.swing.JLabel();
        Contactslabel = new javax.swing.JLabel();
        GrizzlyBearlabel = new javax.swing.JLabel();
        Calculatorlabel = new javax.swing.JLabel();
        Homelabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LegionaireOSlabel.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        LegionaireOSlabel.setForeground(new java.awt.Color(255, 255, 255));
        LegionaireOSlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LegionaireOSlabel.setText("Legionnaire OS Simulator");
        getContentPane().add(LegionaireOSlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 440, 40));

        Menubutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/menu--1-.png"))); // NOI18N
        Menubutton.setContentAreaFilled(false);
        Menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Menubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 120, 120));

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, 60));

        GrizzlyBearbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/icon_billing--1-.png"))); // NOI18N
        GrizzlyBearbutton.setContentAreaFilled(false);
        GrizzlyBearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrizzlyBearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(GrizzlyBearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 120, -1));

        Calculatorbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/calculator-icon--2-.png"))); // NOI18N
        Calculatorbutton.setContentAreaFilled(false);
        Calculatorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Calculatorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 110, 120));

        Contactsbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/contacts icon.png"))); // NOI18N
        Contactsbutton.setContentAreaFilled(false);
        Contactsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Contactsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 120));

        BullsandCowsbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/game icon.png"))); // NOI18N
        BullsandCowsbutton.setBorder(null);
        BullsandCowsbutton.setContentAreaFilled(false);
        BullsandCowsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BullsandCowsbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(BullsandCowsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 110, 110));

        BullsandCowslabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        BullsandCowslabel.setForeground(new java.awt.Color(255, 255, 255));
        BullsandCowslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BullsandCowslabel.setText("Bulls and Cows");
        getContentPane().add(BullsandCowslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, 20));

        Contactslabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Contactslabel.setForeground(new java.awt.Color(255, 255, 255));
        Contactslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contactslabel.setText("Contacts");
        getContentPane().add(Contactslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 100, 20));

        GrizzlyBearlabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        GrizzlyBearlabel.setForeground(new java.awt.Color(255, 255, 255));
        GrizzlyBearlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GrizzlyBearlabel.setText("Grizzly Bear");
        getContentPane().add(GrizzlyBearlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 140, 30));

        Calculatorlabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Calculatorlabel.setForeground(new java.awt.Color(255, 255, 255));
        Calculatorlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calculatorlabel.setText("Calculator+");
        getContentPane().add(Calculatorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 130, 30));

        Homelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back3.jpg"))); // NOI18N
        Homelabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Homelabel.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Mandeep\\Documents\\IP Project Mandeep, Ajay\\back 9.jpg")); // NOI18N
        getContentPane().add(Homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Helpmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpmenuActionPerformed(evt);
            }
        });

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Login().setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void MenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubuttonActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenubuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1026, 694);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if (JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void HelpmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpmenuActionPerformed

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if (JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void ContactsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsbuttonActionPerformed
new Contacts_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactsbuttonActionPerformed

    private void GrizzlyBearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrizzlyBearbuttonActionPerformed
new GrizzlyBear_Login().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_GrizzlyBearbuttonActionPerformed

    private void CalculatorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorbuttonActionPerformed
new Calculator_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculatorbuttonActionPerformed

    private void BullsandCowsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BullsandCowsbuttonActionPerformed
new Bulls_and_Cows().setVisible(true);
new Enter_no().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BullsandCowsbuttonActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton BullsandCowsbutton;
    private javax.swing.JLabel BullsandCowslabel;
    private javax.swing.JButton Calculatorbutton;
    private javax.swing.JLabel Calculatorlabel;
    private javax.swing.JButton Contactsbutton;
    private javax.swing.JLabel Contactslabel;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JButton GrizzlyBearbutton;
    private javax.swing.JLabel GrizzlyBearlabel;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    public javax.swing.JLabel Homelabel;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JLabel LegionaireOSlabel;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Menubutton;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    // End of variables declaration//GEN-END:variables
}
