package legionnaire_os;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

public class Login extends javax.swing.JFrame {

    String curusername;
    String curpassword;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

//---------------------JDBC part getting username and password--------------------//
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Select * from userpass";
        ResultSet rs = stmt.executeQuery(query);
        if (rs.first()) 
            {
                curusername = rs.getString(1);
                curpassword = rs.getString(2);
            }
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }

//---------------------JDBC part getting background--------------------------------//
try 
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManDroid", "root", "mandy15012001");
                Statement stmt = con.createStatement();
                String query = "Select * from backgrounds";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.first()) 
                    {
                        String loginbackg = rs.getString(2);
                        Loginlabel.setIcon(new ImageIcon(getClass().getResource(loginbackg)));
                    }
            } 
        catch (Exception e) 
            {
                JOptionPane.showMessageDialog(this, "Error in Connectivity!");
            }

//---------------------JDBC part getting avatar--------------------------------//
try 
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
                Statement stmt = con.createStatement();
                String query = "Select * from useravatar";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.first()) 
                    {
                        String avatar = rs.getString(1);
                        Userlabel.setIcon(new ImageIcon(getClass().getResource(avatar)));
                    }
            } 
        catch (Exception e) 
            {
                JOptionPane.showMessageDialog(this, "Error in Connectivity!");
            }

/**********************************************************************************************************/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hellolabel = new javax.swing.JLabel();
        Userlabel = new javax.swing.JLabel();
        Usernamelabel = new javax.swing.JLabel();
        Passwordlabel = new javax.swing.JLabel();
        UserTF = new javax.swing.JTextField();
        PassTF = new javax.swing.JPasswordField();
        Submitbutton = new javax.swing.JButton();
        Cancelbutton = new javax.swing.JButton();
        Loginlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hellolabel.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        Hellolabel.setForeground(new java.awt.Color(255, 255, 255));
        Hellolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hellolabel.setText("Hello, Leggionnaire User!!");
        getContentPane().add(Hellolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1020, 80));

        Userlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Userlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/user12.png"))); // NOI18N
        getContentPane().add(Userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1020, 170));

        Usernamelabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        Usernamelabel.setText("Enter your Username");
        getContentPane().add(Usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 260, 40));

        Passwordlabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        Passwordlabel.setText("Password");
        getContentPane().add(Passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, 40));

        UserTF.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        UserTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                UserTFCaretUpdate(evt);
            }
        });
        getContentPane().add(UserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 230, 40));

        PassTF.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        PassTF.setForeground(java.awt.Color.red);
        PassTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PassTF.setText("Password");
        PassTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                PassTFCaretUpdate(evt);
            }
        });
        PassTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassTFMouseClicked(evt);
            }
        });
        getContentPane().add(PassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 230, 40));

        Submitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/tick_red (1).png"))); // NOI18N
        Submitbutton.setContentAreaFilled(false);
        Submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Submitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 60, 60));

        Cancelbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/x-mark-3-xxl (1).png"))); // NOI18N
        Cancelbutton.setContentAreaFilled(false);
        Cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 60, 60));

        Loginlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/back1.jpg"))); // NOI18N
        Loginlabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Loginlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed
String user = UserTF.getText();
String pass = new String(PassTF.getPassword());
if (user.equalsIgnoreCase(curusername) && pass.equalsIgnoreCase(curpassword)) 
{
    JOptionPane.showMessageDialog(this,"You have been successfully logged in." );
    new Home().setVisible(true);
    this.dispose();
} 
else 
{
    JOptionPane.showMessageDialog(this, "Username and Password do not match. Please try again.", "Incorrect username or password", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_SubmitbuttonActionPerformed

    private void CancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbuttonActionPerformed
if (JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
{
    System.exit(0);
}
    }//GEN-LAST:event_CancelbuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1026, 575);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void PassTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassTFMouseClicked
PassTF.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTFMouseClicked

    private void UserTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_UserTFCaretUpdate
String user = UserTF.getText();
if(user.equalsIgnoreCase(curusername))
{
    UserTF.setForeground(Color.GREEN);
}
else
{
    UserTF.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTFCaretUpdate

    private void PassTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_PassTFCaretUpdate
String pass = new String(PassTF.getPassword());
if(pass.equalsIgnoreCase(curpassword))
{
    PassTF.setForeground(Color.GREEN);
}
else
{
    PassTF.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTFCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbutton;
    private javax.swing.JLabel Hellolabel;
    public javax.swing.JLabel Loginlabel;
    private javax.swing.JPasswordField PassTF;
    private javax.swing.JLabel Passwordlabel;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JTextField UserTF;
    public javax.swing.JLabel Userlabel;
    private javax.swing.JLabel Usernamelabel;
    // End of variables declaration//GEN-END:variables
}
