package legionnaire_os;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mandeep M. Dalavi
 */
public class Security_Setting extends javax.swing.JFrame {

    String curusername, curpassword;
    String user, pass, newuser, newpass;
    /**
     * Creates new form Security_Settings
     */
    public Security_Setting() {
        initComponents();
        
//---------------------JDBC part getting username and password--------------------//
try 
    {
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
        Statement stmt = con.createStatement();
        String query = "Select * from userpass";
        ResultSet rs = stmt.executeQuery(query);
        if (rs.first()) 
            {
                curusername = rs.getString(1);
                curpassword = rs.getString(2);
            }
    } 
catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error in Connectivity!");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Powerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Powerbutton = new javax.swing.JButton();
        Securitylabel = new javax.swing.JLabel();
        ChangeUserlabel = new javax.swing.JLabel();
        ChangePasslabel = new javax.swing.JLabel();
        CurUserlabel = new javax.swing.JLabel();
        CurPasslabel = new javax.swing.JLabel();
        NewUserlabel = new javax.swing.JLabel();
        Curuserlabel = new javax.swing.JLabel();
        Curpasslabel = new javax.swing.JLabel();
        NewPasslabel = new javax.swing.JLabel();
        CurUserleft = new javax.swing.JTextField();
        NewUserleft = new javax.swing.JTextField();
        NewPassright = new javax.swing.JTextField();
        CurUserright = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Submitright = new javax.swing.JButton();
        Submitleft = new javax.swing.JButton();
        CurPassleft = new javax.swing.JPasswordField();
        CurPassright = new javax.swing.JPasswordField();
        SecurSetlabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Filemenu = new javax.swing.JMenu();
        JumpHomemenu = new javax.swing.JMenuItem();
        JumpAppmenu = new javax.swing.JMenuItem();
        ExitOSmenu = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUsmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Powerpanel.setBackground(new java.awt.Color(255, 255, 255));

        Homebutton.setBackground(new java.awt.Color(255, 255, 255));
        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/home-home-icon-90085 (2).png"))); // NOI18N
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/android-system-back (2).png"))); // NOI18N
        Backbutton.setContentAreaFilled(false);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Powerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/power-xxl (1).png"))); // NOI18N
        Powerbutton.setContentAreaFilled(false);
        Powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerpanelLayout = new javax.swing.GroupLayout(Powerpanel);
        Powerpanel.setLayout(PowerpanelLayout);
        PowerpanelLayout.setHorizontalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PowerpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Powerbutton)
                .addGap(318, 318, 318)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(56, 56, 56))
        );
        PowerpanelLayout.setVerticalGroup(
            PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerpanelLayout.createSequentialGroup()
                .addGroup(PowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Powerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 60));

        Securitylabel.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Securitylabel.setForeground(new java.awt.Color(255, 255, 255));
        Securitylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Securitylabel.setText("Security Setting");
        getContentPane().add(Securitylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 410, -1));

        ChangeUserlabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ChangeUserlabel.setForeground(new java.awt.Color(255, 255, 255));
        ChangeUserlabel.setText("Change Username");
        getContentPane().add(ChangeUserlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        ChangePasslabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ChangePasslabel.setForeground(new java.awt.Color(255, 255, 255));
        ChangePasslabel.setText("Change Password");
        getContentPane().add(ChangePasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        CurUserlabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CurUserlabel.setForeground(new java.awt.Color(255, 255, 255));
        CurUserlabel.setText("Current Username");
        getContentPane().add(CurUserlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, -1));

        CurPasslabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CurPasslabel.setForeground(new java.awt.Color(255, 255, 255));
        CurPasslabel.setText("Current Password");
        getContentPane().add(CurPasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, -1));

        NewUserlabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        NewUserlabel.setForeground(new java.awt.Color(255, 255, 255));
        NewUserlabel.setText("New Username");
        getContentPane().add(NewUserlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, -1));

        Curuserlabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Curuserlabel.setForeground(new java.awt.Color(255, 255, 255));
        Curuserlabel.setText("Current Username");
        getContentPane().add(Curuserlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 220, -1));

        Curpasslabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Curpasslabel.setForeground(new java.awt.Color(255, 255, 255));
        Curpasslabel.setText("Current Password");
        getContentPane().add(Curpasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 220, -1));

        NewPasslabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        NewPasslabel.setForeground(new java.awt.Color(255, 255, 255));
        NewPasslabel.setText("New Password");
        getContentPane().add(NewPasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 220, -1));

        CurUserleft.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CurUserleft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurUserleft.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                CurUserleftCaretUpdate(evt);
            }
        });
        getContentPane().add(CurUserleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 230, 30));

        NewUserleft.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        NewUserleft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(NewUserleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 230, 30));

        NewPassright.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        NewPassright.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(NewPassright, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 230, 30));

        CurUserright.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CurUserright.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurUserright.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                CurUserrightCaretUpdate(evt);
            }
        });
        getContentPane().add(CurUserright, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 230, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 10, 180));

        Submitright.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Submitright.setText("Submit");
        Submitright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitrightActionPerformed(evt);
            }
        });
        getContentPane().add(Submitright, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 120, -1));

        Submitleft.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Submitleft.setText("Submit");
        Submitleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitleftActionPerformed(evt);
            }
        });
        getContentPane().add(Submitleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 120, -1));

        CurPassleft.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        CurPassleft.setForeground(java.awt.Color.red);
        CurPassleft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurPassleft.setText("Password");
        CurPassleft.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CurPassleft.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                CurPassleftCaretUpdate(evt);
            }
        });
        CurPassleft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurPassleftMouseClicked(evt);
            }
        });
        CurPassleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurPassleftActionPerformed(evt);
            }
        });
        getContentPane().add(CurPassleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 230, 30));

        CurPassright.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        CurPassright.setForeground(java.awt.Color.red);
        CurPassright.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurPassright.setText("Password");
        CurPassright.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                CurPassrightCaretUpdate(evt);
            }
        });
        CurPassright.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurPassrightMouseClicked(evt);
            }
        });
        getContentPane().add(CurPassright, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 230, 30));

        SecurSetlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legionnaire_os/OS Backs/settingback3.png"))); // NOI18N
        getContentPane().add(SecurSetlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Filemenu.setText("File");
        Filemenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JumpHomemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JumpHomemenu.setText("Jump to HomeScreen");
        JumpHomemenu.setOpaque(true);
        JumpHomemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpHomemenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpHomemenu);

        JumpAppmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JumpAppmenu.setText("Jump to AppDrawer");
        JumpAppmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpAppmenuActionPerformed(evt);
            }
        });
        Filemenu.add(JumpAppmenu);

        ExitOSmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitOSmenu.setText("Exit Legionnaire OS");
        ExitOSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOSmenuActionPerformed(evt);
            }
        });
        Filemenu.add(ExitOSmenu);

        Menu.add(Filemenu);

        Helpmenu.setText("Help");
        Helpmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AboutUsmenu.setText("About Us..");
        AboutUsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsmenuActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUsmenu);

        Menu.add(Helpmenu);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
new Setting_App().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void JumpHomemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpHomemenuActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpHomemenuActionPerformed

    private void JumpAppmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpAppmenuActionPerformed
new Apps().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpAppmenuActionPerformed

    private void ExitOSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOSmenuActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitOSmenuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setResizable(true);
this.setSize(1025, 707);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
new Home().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void PowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbuttonActionPerformed
if(JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION)
{
    System.exit(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbuttonActionPerformed

    private void AboutUsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsmenuActionPerformed
new About_Us().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsmenuActionPerformed

    private void SubmitleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitleftActionPerformed
user = CurUserleft.getText();
newuser = NewUserleft.getText();
pass = new String(CurPassleft.getPassword());
if(user.isEmpty() || pass.isEmpty() || newuser.isEmpty())
{
    JOptionPane.showMessageDialog(this, "Fields can't be Empty", "Caution", JOptionPane.WARNING_MESSAGE);
}
else
{
    if (user.equalsIgnoreCase(curusername) && pass.equalsIgnoreCase(curpassword)) 
    {
        try 
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
            Statement stmt = con.createStatement();
            String query = "UPDATE userpass SET username = '"+newuser+"' WHERE ( username = '"+user+"' && password = '"+pass+"' ;";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.first()) 
                {
                    curusername = rs.getString(1);
                    curpassword = rs.getString(2);
                    JOptionPane.showMessageDialog(this,"Username changed successfully." );
                }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error in Connectivity!");
        }
    } 
    else 
    {
        JOptionPane.showMessageDialog(this, "Username and Password doesn't match. Please try again.", "Incorrect username or password", JOptionPane.ERROR_MESSAGE);
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitleftActionPerformed

    private void SubmitrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitrightActionPerformed
user = CurUserright.getText();
newpass = NewPassright.getText();
pass = new String(CurPassright.getPassword());
if(user.isEmpty() || pass.isEmpty() || newuser.isEmpty())
{
    JOptionPane.showMessageDialog(this, "Fields can't be Empty", "Caution", JOptionPane.WARNING_MESSAGE);
}
else
{
    if (user.equalsIgnoreCase(curusername) && pass.equalsIgnoreCase(curpassword)) 
    {
        try 
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mandroid", "root", "mandy15012001");
            Statement stmt = con.createStatement();
            String query = "UPDATE userpass SET password = '"+newpass+"' WHERE ( username = '"+user+"' && password = '"+pass+"' ;";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.first()) 
                {
                    curusername = rs.getString(1);
                    curpassword = rs.getString(2);
                    JOptionPane.showMessageDialog(this,"Username changed successfully." );
                }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error in Connectivity!");
        }
    } 
    else 
    {
        JOptionPane.showMessageDialog(this, "Username and Password doesn't match. Please try again.", "Incorrect username or password", JOptionPane.ERROR_MESSAGE);
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitrightActionPerformed

    private void CurPassleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurPassleftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurPassleftActionPerformed

    private void CurPassleftCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_CurPassleftCaretUpdate
pass = new String(CurPassleft.getPassword());
if (pass.equalsIgnoreCase(curpassword)) 
{
    CurPassleft.setForeground(Color.GREEN);
} 
else 
{
    CurPassleft.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_CurPassleftCaretUpdate

    private void CurPassrightCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_CurPassrightCaretUpdate
pass = new String(CurPassright.getPassword());
if (pass.equalsIgnoreCase(curpassword)) 
{
    CurPassright.setForeground(Color.GREEN);
} 
else 
{
    CurPassright.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_CurPassrightCaretUpdate

    private void CurPassleftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurPassleftMouseClicked
CurPassleft.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_CurPassleftMouseClicked

    private void CurPassrightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurPassrightMouseClicked
CurPassright.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_CurPassrightMouseClicked

    private void CurUserleftCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_CurUserleftCaretUpdate
user = CurUserleft.getText();
if(user.equalsIgnoreCase(curusername))
{
    CurUserleft.setForeground(Color.GREEN);
}
else
{
    CurUserleft.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_CurUserleftCaretUpdate

    private void CurUserrightCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_CurUserrightCaretUpdate
user = CurUserright.getText();
if(user.equalsIgnoreCase(curusername))
{
    CurUserright.setForeground(Color.GREEN);
}
else
{
    CurUserright.setForeground(Color.RED);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_CurUserrightCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Security_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Security_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Security_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Security_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Security_Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsmenu;
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel ChangePasslabel;
    private javax.swing.JLabel ChangeUserlabel;
    private javax.swing.JLabel CurPasslabel;
    private javax.swing.JPasswordField CurPassleft;
    private javax.swing.JPasswordField CurPassright;
    private javax.swing.JLabel CurUserlabel;
    private javax.swing.JTextField CurUserleft;
    private javax.swing.JTextField CurUserright;
    private javax.swing.JLabel Curpasslabel;
    private javax.swing.JLabel Curuserlabel;
    private javax.swing.JMenuItem ExitOSmenu;
    private javax.swing.JMenu Filemenu;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JButton Homebutton;
    private javax.swing.JMenuItem JumpAppmenu;
    private javax.swing.JMenuItem JumpHomemenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel NewPasslabel;
    private javax.swing.JTextField NewPassright;
    private javax.swing.JLabel NewUserlabel;
    private javax.swing.JTextField NewUserleft;
    private javax.swing.JButton Powerbutton;
    private javax.swing.JPanel Powerpanel;
    private javax.swing.JLabel SecurSetlabel;
    private javax.swing.JLabel Securitylabel;
    private javax.swing.JButton Submitleft;
    private javax.swing.JButton Submitright;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
